In [1]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [2]:
import torch

In [3]:
import re
from transformers import BertForSequenceClassification

In [4]:
tokenizer = AutoTokenizer.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')

In [5]:
model = BertForSequenceClassification.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')

In [6]:
import pandas as pd

In [7]:
xvc = pd.read_csv('Comment_likes.csv')

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1929031754.py:1: DtypeWarning: Columns (2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,41,43,45,47,49,51,53,55,57,59,61,63,65,67,69,71,73,75,77,79,81,83,85,87,89,91,93,95,97,99,101,103,105,107,109,111,113,115,117,119,121,123,125,127,129,131,133,135,137,139,141,143,145,147,149,151,153,155,157,159,161,163,165,167,169,171,173,175,177,179,181,183,185,187,189,191,193,195,197,199,201,203,205,207,209,211,213,215,217,219,221,223,225,227,229,231,233,235,237,239,241,243,245,247,249,251,253,255,257,259,261,263,265,267,269,271,273,275,277,279,281,283,285,287,289,291,293,295,297,299,301,303,305,307,309,311,313,315,317,319,321,323,325,327,329,331,333,335,337,339,341,343,345,347,349,351,353,355,357,359,361,363,365,367,369,371,373,375,377,379,381,383,385,387,389,391,393,395,397,399,401,403,405,407,409,411,413,415,417,419,421,423,425,427,429,431,433,435,437,439,441,443,445,447,449,451,453,455,457,459,461,463,465,467,469,471,473,475,477,479,481,483,485,487,489,491,493,495,497,499,501,503,505,507,509,511,513,515,517,519,521,523,525,527,529,531,533,535,537,539,541,543,545,547,549,551,553,555,557,559,561,563,565,567,569,571,573,575,577,579,581,583,585,587,589,591,593,595,597,599,601,603,605,607,609,611,613,615,617,619,621,623,625,627,629,631,633,635,637,639,641,643,645,647,649,651,653,655,657,659,661,663,665,667,669,671,673,675,677,679,681,683,685,687,689,691,693,695,697,699,701,703,705,707,709,711,713,715,717,719,721,723,725,727,729,731,733,735,737,739,741,743,745,747,749,751,753,755,757,759,761,763,765,767,769,771,773,775,777,779,781,783,785,787,789,791,793,795,797,799,801,803,805,807,809,811,813,815,817,819,821,823,825,827,829,831,833,835,837,839,841,843,845,847,849,851,853,855,857,861,863,865,867,869,871,873,875,877,879,881,883,885,887,889,891,893,895,897,899,901,903,905,907,909,911,913,915,917,919,921,923,925,927,929,931,933,935,937,939,941,943,945,947,949,951,953,955,957,959,961,963,965,967,969,971,973,975,977,979,981,983,985,987,989,991,993,995,997,999,1001,1003,1005,1007,1009,1011,1013,1015,1017,1019,1021,1023,1025,1027,1029,1031,1033,1035,1037,1039,1041,1043,1045,1047,1049,1051,1053,1055,1057,1059,1061,1063,1065,1067,1069,1071,1073,1075,1077,1079,1081,1083,1085,1087,1089,1091,1093,1095,1097,1099,1101,1103,1105,1107,1109,1111,1113,1115,1117,1119,1121,1123,1125,1127,1129,1131,1133,1135,1137,1139,1141,1143,1145,1147,1149,1151,1153,1155,1157,1159,1161,1163,1165,1167,1169,1171,1173,1175,1177,1179,1181,1183,1185,1187,1189,1191,1193,1195,1197,1199,1201,1203,1205,1207,1209,1211,1213,1215,1217,1219,1221,1223,1225,1227,1229,1231,1233,1235,1237,1239,1241,1243,1245,1247,1249,1251,1253,1255,1257,1259,1261,1263,1265,1267,1269,1271,1273,1275,1277,1279,1281,1283,1285,1287,1289,1291,1293,1295,1297,1299,1301,1303,1305,1307,1309,1311,1313,1315,1317,1319,1321,1323,1325,1327,1329,1331,1333,1335,1337,1339,1341,1343,1345,1347,1349,1351,1353,1355,1357,1359,1361,1363,1365,1367,1369,1371,1373,1375,1377,1379,1381,1383,1385,1387,1389,1391,1393,1395,1397,1399,1401,1403,1405,1407,1409,1411,1413,1415,1417,1419,1421,1423,1425,1427,1429,1431,1433,1435,1437,1439,1441,1443,1445,1447,1449,1451,1453,1455,1457,1459,1461,1463,1465,1467,1469,1471,1473,1475,1477,1479,1481,1483,1485,1487,1489,1491,1493,1495,1497,1499,1501,1503,1505,1507,1509,1511,1513,1515,1517,1519,1521,1523,1525,1527,1529,1531,1533,1535,1537,1539,1541,1543,1545,1547,1549,1551,1553,1555,1557,1559,1561,1563,1565,1567,1569,1571,1573,1575,1577,1579,1581,1583,1585,1587,1589,1591,1593,1595,1597,1599,1601,1603,1605,1607,1609,1611,1613,1615,1617,1619,1621,1623,1625,1627,1629,1631,1633,1635,1637,1639,1641,1643,1645,1647,1649,1651,1653,1655,1657,1659,1661,1663,1665,1667,1669,1671,1673,1675,1677,1679,1681,1683,1685,1687,1689,1691,1693,1695,1697,1699,1701,1703,1705,1707,1709,1711,1713,1715,1717,1719,1721,1723,1725,1727,1729,1731,1733,1735,1737,1739,1741,1743,1745,1747,1749,1751,1753,1755,1757,1759,1761,1763,1765,1767,1769,1771,1773,1775,1777,1779,1781,1783,1785,1787,1789,1791,1793,1795,1797,1799,1801,1803,1805,1807,1809,1811,1813,1815,1817,1819,1821,1823,1825,1827,1829,1831,1833,1835,1837,1839,1841,1843,1845,1847,1849,1851,1853,1855,1857,1859,1861,1863,1865,1867,1869,1871,1873,1875,1877,1879,1881,1883,1885,1887,1889,1891,1893,1895,1897,1899,1901,1903,1905,1907,1909,1911,1913,1915,1917,1919,1921,1923,1925,1927,1929,1931,1933,1935,1937,1939,1941,1943,1945,1947,1949,1951,1953,1955,1957,1959,1961,1963,1965,1967,1969,1971,1973,1975,1977,1979,1981,1983,1985,1987,1989,1991,1993,1995,1997,1999,2001,2003,2005,2007,2009,2011,2013,2015,2017,2019,2021,2023,2025,2027,2029,2031,2033,2035,2037,2039,2041,2043,2045,2047,2049,2051,2053,2055,2057,2059,2061,2063,2065,2067,2069,2071,2073,2075,2077,2079,2081,2083,2085,2087,2089,2091,2093,2095,2097,2099,2101,2103,2105,2107,2109,2111,2113,2115,2117,2119,2121,2123,2125,2127,2129,2131,2133,2135,2137,2139,2141,2143,2145,2147,2149,2151,2153,2155,2157,2159,2161,2163,2165,2167,2169,2171,2173,2175,2177,2179,2181,2183,2185,2187,2189,2191,2193,2195,2197,2199,2201,2203,2205,2207,2209,2211,2213,2215,2217,2219,2221,2223,2225,2227,2229,2231,2233,2235,2237,2239,2241,2243,2245,2247,2249,2251,2253,2255,2257,2259,2261,2263,2265,2267,2269,2271,2273,2275,2277,2279,2281,2283,2285,2287,2289,2291,2293,2295,2297,2299,2301,2303,2305,2307,2309,2311,2313,2315,2317,2319,2321,2323,2325,2327,2329,2331,2333,2335,2337,2339,2341,2343,2345,2347,2349,2351,2353,2355,2357,2359,2361,2363,2365,2367,2369,2371,2373,2375,2377,2379,2381,2383,2385,2387,2389,2391,2393,2395,2397,2399,2401,2403,2405,2407,2409,2411,2413,2415,2417,2419,2421,2423,2425,2427,2429,2431,2433,2435,2437,2439,2441,2443,2445,2447,2449,2451,2453,2455,2457,2459,2461,2463,2465,2467,2469,2471,2473,2475,2477,2479,2481,2483,2485,2487,2489,2491,2493,2495,2497,2499,2501,2503,2505,2507,2509,2511,2513,2515,2517,2519,2521,2523,2525,2527,2529,2531,2533,2535,2537,2539,2541,2543,2545,2547,2549,2551,2553,2555,2557,2559,2561,2563,2565,2567,2569,2571,2573,2575,2577,2579,2581,2583,2585,2587,2589,2591,2593,2595,2597,2599,2601,2603,2605,2607,2609,2611,2613,2615,2617,2619,2621,2623,2625,2627,2629,2631,2633,2635,2637,2639,2641,2643,2645,2647,2649,2651,2653,2655,2657,2659,2661,2663,2665,2667,2669,2671,2673,2675,2677,2679,2681,2683,2685,2687,2689,2691,2693,2695,2697,2699,2701,2703,2705,2707,2709,2711,2713,2715,2717,2719,2721,2723,2725,2727,2729,2731,2733,2735,2737,2739,2741,2743,2745,2747,2749,2751,2753,2755,2757,2759,2761,2763,2765,2767,2769,2771,2773,2775,2777,2779,2781,2783,2785,2787,2789,2791,2793,2795,2797,2799,2801,2803,2805,2807,2809,2811,2813,2815,2817,2819,2821,2823,2825,2827,2829,2831,2833,2835,2837,2839,2841,2843,2845,2847,2849,2851,2853,2855,2857,2859,2861,2863,2865,2867,2869,2871,2873,2875,2877,2879,2881,2883,2885,2887,2889,2891,2893,2895,2897,2899,2901,2903,2905,2907,2909,2911,2913,2915,2917,2919,2921,2923,2925,2927,2929,2931,2933,2935,2937,2939,2941,2943,2945,2947,2949,2951,2953,2955,2957,2959,2961,2963,2965,2967,2969,2971,2973,2975,2977,2979,2981,2983,2985,2987,2989,2991,2993,2995,2997,2999,3001,3003,3005,3007,3009,3011,3013,3015,3017,3019,3021,3023,3025,3027,3029,3031,3033,3035,3037,3039,3041,3043,3045,3047,3049,3051,3053,3055,3057,3059,3061,3063,3065,3067,3069,3071,3073,3075,3077,3079,3081,3083,3085,3087,3089,3091,3093,3095,3097,3099,3101,3103,3105,3107,3109,3111,3113,3115,3117,3119,3121,3123,3125,3127,3129,3131,3133,3135,3137,3139,3141,3143,3145,3147,3151,3153,3155,3157,3159,3161,3163,3165,3167,3169,3171,3173,3175,3177,3179,3181,3183,3185,3187,3189,3191,3193,3195,3197,3199,3201,3203,3205,3207,3209,3211,3213,3215,3217,3219,3221,3223,3225,3227,3229,3231) have mixed types. Specify dtype option on import or set low_memory=False.
  xvc = pd.read_csv('Comment_likes.csv')

In [8]:
for i in range(41,3233):
    yy = "Unnamed: {}".format(i)
    xvc = xvc.drop(columns=yy)

In [9]:
xvc

,video_id,comment_1,comment_1_likes,comment_2,comment_2_likes,comment_3,comment_3_likes,comment_4,comment_4_likes,comment_5,...,comment_16,comment_16_likes,comment_17,comment_17_likes,comment_18,comment_18_likes,comment_19,comment_19_likes,comment_20,comment_20_likes
0,--0bCF-iK2E,Can’t wait for him to kiss the badge in front ...,2100.0,"Respect to Dortmund fans,must be sad losing him.",1800.0,One of the most talented players Bundesliga ha...,40.0,It's so heartbreaking look at Sancho playing f...,12.0,wish him well in manchester united,...,here after his first Man United goal. What a p...,2.0,He is forever a joy to watch. I wish you all t...,0.0,Saw him play for England the other day for fir...,0.0,DANKE JADON💛🖤,38.0,"Bringing that magic to Old Trafford,💥💥",1.0
1,--14w5SOEUs,RIP Takeoff. The world is gonna miss you and y...,982.0,I love how Migos knows every assignment and to...,3.0,This video just puts a smile on my face 😂,0.0,It’s been about 48 hrs since Takeoff’s passing...,438.0,The amount of swag these 3 possess is unmatche...,...,"Migos was so fresh, so fly. Undoubtedly, one ...",36.0,Wow!!! This is hip hop. I am from the East Coa...,47.0,The way Migos flow on this track is just incre...,95.0,This is exactly why Migos need to be appreciat...,156.0,HIPHOP WILL NEVER BE THE SAME😭😭😭,29.0
2,--40TEbZ9Is,"I get that she isn't a nobody, but to see some...",1100.0,You can tell Juno is not even that upset that ...,1000.0,"“There’s no Rebecca without Keeley” god, my te...",2800.0,Hannah looking straight into Jason's eyes sayi...,1500.0,That was the shortest episode of Ted Lasso I h...,...,I feel like she really didn’t expect this and ...,436.0,I keep telling people how amazing this show is...,44.0,I nearly cried when I saw Jason's face. so muc...,34.0,This is the kind of speech we love. genuine fu...,151.0,Best speech of the night! Hannah seems like su...,233.0
3,--4tfbSyYDE,１７の男ですが、JAMになっていいですか？,1500.0,ファイナルの2曲をこの制服でパフォーマンスしてくれるなんて。すごく嬉しいのに、すごく泣けてき...,474.0,木全が手の指のところにJAMって書いてるところほんと可愛いし、ほんと好きだわ,31.0,ゆるく踊ってるメンバーが多い中、蓮くんはずっとキレキレに踊ってて嬉しいし、カッコいい！！,4.0,このMVを見ると、切なくて、愛おしくて、JO1って素晴らしいってなる。,...,JO1の歴史と共に私達JAMも生きている事に日々感謝しています\n彼らの努力が花開いて行く過...,30.0,ねえ…瑠姫くんさすがにかっこよすぎるって……,25.0,いっしょに成長していくというのを凄く感じさせられた1年でした。コロナの影響もあって、直接会っ...,15.0,YOUNGの蓮くんもものすごく良くて定期的に見に来てしまう,42.0,1o1の時のよなは歌の実力があるのにメインボーカルも出来なかったからもどかしかった。\nでも...,279.0
4,#NAME?,🚧 Keep up with all my projects here: https://p...,146.0,Your mechanically stabilized earth video inspi...,2500.0,"Years ago as a baby apprentice electrician, I ...",1000.0,I’ve been a safety person for over 25 years wi...,81.0,I love that he’s a civil engineer and his name...,...,It's only a very small exaggeration to say tha...,1.0,You're single-handedly saving my interest in m...,4.0,"As a new geologist at a geotech firm, I’m lear...",4.0,"I live in a very old Italian city, it is very ...",1.0,"I also learned that in Japan, retaining walls ...",880.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37478,zzd4ydafGR0,'DESTINED 2 WIN' OUT NOW !! https://liltjay.ln...,13000.0,claim your “BEFORE A MILLION” ticket 🎫,2200.0,Lil Tjay don't miss.,52000.0,A message to the next generations: Don't let t...,2300.0,"I hope you pull through bro, i know this is a ...",...,Essa música marcou uma fase da minha vida e te...,20.0,"can’t lose another legend man, keep fighting t...",239.0,Steady callin' my phone\nI done told you befor...,94.0,Pode comemorar vc achou a música que vc tanto ...,4.0,Imagine speeding down a highway at night after...,896.0
37479,zziBybeSAtw,That 2nd Half from the Lakers truly shows how ...,202.0,Montrezl Harrell is going crazy with the rebou...,1500.0,The Lakers have such a good bench and good def...,199.0,"Dang man, I can't wait to see the fans back in...",15.0,The Lakers are such a solid team in every aspe...,...,Another great effort by ALL the Lakers. Great ...,0.0,"Montrezl is ballin out there, what a differenc...",1000.0,So we not going talk about how Brandon Ingram ...,3.0,Bruh I could see Lebron dominating even if its...,91.0,4 straight game that they blowout their oppone...,10.0
37480,zzk09ESX7e0,"For anyone here, this song is NOT their farewe...",4700.0,You know what? People may not str3am some of t...,298.0,This song deserves justice. Cannot believe it ...,7.0,Best song falan,8.0,This song hits so different after watching the...,...,"Decided to watch this after the docu, man this...",56.0,Siempre te amaré Mamamoo.,5.0,"Despite the group ""seemingly"" slowing down, ea...",34.0,Best voices in the industry.\nBest women group...,17000.0,Reinas Vocales!!!,32.0
37481,zzmQEb0Em5I,Foi um prazer passar esta tarde com vocês deba...,3000.0,"Petição pro Escudero vir aqui mais vezes, pois...",224.0,"Castanhari, mitico e igão sendo engolidos, arg...",37.0,"Chifre é igual consórcio, uma hora você é cont...",1700.0,"ze graça parece ter estudado o convidado, muit...",...,Gostaria de agradecer ao canal por tão bela en...,0.0,"Poucos conhecem o Escudero, ainda bem que ele ...",3.0,"Cara, sendo contemporâneo do Lordão, compartil...",3.0,Mudei completamente a imagem que eu tinha do E...,23.0,Curto muito o trabalho do Escudero.,190.0
37482,zzxPZwaA-8w,"If you didn't know Leicester is a good team, B...",203.0,"As a Chelsea fan, I have never said this, but ...",2200.0,It’s like watching the old Gareth bale playing...,1700.0,As a fan of Chelsea I say thank you to Tottenh...,715.0,Bale just single handedly destroyed Leicester....,...,Bale was involved in two goals.\r\nKane was in...,93.0,"1:22 Good to see SON, KANE, BALE teamwork toge...",310.0,"“BALE!”, I can’t explain how I felt watching t...",69.0,Thank you gareth bale!\nFrom a chelsea fan,559.0,great way to end what's been a horrible season...,7.0

In [16]:
stt = xvc['comment_1'][1]

In [17]:
stt

'RIP Takeoff. The world is gonna miss you and your talent. The flow on this one was just legendary!'

In [18]:
type(stt)

str

In [19]:
result = model(tokenizer.encode(stt, return_tensors='pt', truncation=True, max_length=512))
xt = int(torch.argmax(result.logits))+1

In [20]:
xt

5

In [22]:
for i in range(1,21):
    xvc["comment_{}_rate".format(i)]=0

In [23]:
xvc

,video_id,comment_1,comment_1_likes,comment_2,comment_2_likes,comment_3,comment_3_likes,comment_4,comment_4_likes,comment_5,...,comment_11_rate,comment_12_rate,comment_13_rate,comment_14_rate,comment_15_rate,comment_16_rate,comment_17_rate,comment_18_rate,comment_19_rate,comment_20_rate
0,--0bCF-iK2E,Can’t wait for him to kiss the badge in front ...,2100.0,"Respect to Dortmund fans,must be sad losing him.",1800.0,One of the most talented players Bundesliga ha...,40.0,It's so heartbreaking look at Sancho playing f...,12.0,wish him well in manchester united,...,0,0,0,0,0,0,0,0,0,0
1,--14w5SOEUs,RIP Takeoff. The world is gonna miss you and y...,982.0,I love how Migos knows every assignment and to...,3.0,This video just puts a smile on my face 😂,0.0,It’s been about 48 hrs since Takeoff’s passing...,438.0,The amount of swag these 3 possess is unmatche...,...,0,0,0,0,0,0,0,0,0,0
2,--40TEbZ9Is,"I get that she isn't a nobody, but to see some...",1100.0,You can tell Juno is not even that upset that ...,1000.0,"“There’s no Rebecca without Keeley” god, my te...",2800.0,Hannah looking straight into Jason's eyes sayi...,1500.0,That was the shortest episode of Ted Lasso I h...,...,0,0,0,0,0,0,0,0,0,0
3,--4tfbSyYDE,１７の男ですが、JAMになっていいですか？,1500.0,ファイナルの2曲をこの制服でパフォーマンスしてくれるなんて。すごく嬉しいのに、すごく泣けてき...,474.0,木全が手の指のところにJAMって書いてるところほんと可愛いし、ほんと好きだわ,31.0,ゆるく踊ってるメンバーが多い中、蓮くんはずっとキレキレに踊ってて嬉しいし、カッコいい！！,4.0,このMVを見ると、切なくて、愛おしくて、JO1って素晴らしいってなる。,...,0,0,0,0,0,0,0,0,0,0
4,#NAME?,🚧 Keep up with all my projects here: https://p...,146.0,Your mechanically stabilized earth video inspi...,2500.0,"Years ago as a baby apprentice electrician, I ...",1000.0,I’ve been a safety person for over 25 years wi...,81.0,I love that he’s a civil engineer and his name...,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37478,zzd4ydafGR0,'DESTINED 2 WIN' OUT NOW !! https://liltjay.ln...,13000.0,claim your “BEFORE A MILLION” ticket 🎫,2200.0,Lil Tjay don't miss.,52000.0,A message to the next generations: Don't let t...,2300.0,"I hope you pull through bro, i know this is a ...",...,0,0,0,0,0,0,0,0,0,0
37479,zziBybeSAtw,That 2nd Half from the Lakers truly shows how ...,202.0,Montrezl Harrell is going crazy with the rebou...,1500.0,The Lakers have such a good bench and good def...,199.0,"Dang man, I can't wait to see the fans back in...",15.0,The Lakers are such a solid team in every aspe...,...,0,0,0,0,0,0,0,0,0,0
37480,zzk09ESX7e0,"For anyone here, this song is NOT their farewe...",4700.0,You know what? People may not str3am some of t...,298.0,This song deserves justice. Cannot believe it ...,7.0,Best song falan,8.0,This song hits so different after watching the...,...,0,0,0,0,0,0,0,0,0,0
37481,zzmQEb0Em5I,Foi um prazer passar esta tarde com vocês deba...,3000.0,"Petição pro Escudero vir aqui mais vezes, pois...",224.0,"Castanhari, mitico e igão sendo engolidos, arg...",37.0,"Chifre é igual consórcio, uma hora você é cont...",1700.0,"ze graça parece ter estudado o convidado, muit...",...,0,0,0,0,0,0,0,0,0,0
37482,zzxPZwaA-8w,"If you didn't know Leicester is a good team, B...",203.0,"As a Chelsea fan, I have never said this, but ...",2200.0,It’s like watching the old Gareth bale playing...,1700.0,As a fan of Chelsea I say thank you to Tottenh...,715.0,Bale just single handedly destroyed Leicester....,...,0,0,0,0,0,0,0,0,0,0

In [29]:
xvc = xvc[xvc.video_id != '#NAME?']

In [30]:
xvc

,video_id,comment_1,comment_1_likes,comment_2,comment_2_likes,comment_3,comment_3_likes,comment_4,comment_4_likes,comment_5,...,comment_11_rate,comment_12_rate,comment_13_rate,comment_14_rate,comment_15_rate,comment_16_rate,comment_17_rate,comment_18_rate,comment_19_rate,comment_20_rate
0,--0bCF-iK2E,Can’t wait for him to kiss the badge in front ...,2100.0,"Respect to Dortmund fans,must be sad losing him.",1800.0,One of the most talented players Bundesliga ha...,40.0,It's so heartbreaking look at Sancho playing f...,12.0,wish him well in manchester united,...,0,0,0,0,0,0,0,0,0,0
1,--14w5SOEUs,RIP Takeoff. The world is gonna miss you and y...,982.0,I love how Migos knows every assignment and to...,3.0,This video just puts a smile on my face 😂,0.0,It’s been about 48 hrs since Takeoff’s passing...,438.0,The amount of swag these 3 possess is unmatche...,...,0,0,0,0,0,0,0,0,0,0
2,--40TEbZ9Is,"I get that she isn't a nobody, but to see some...",1100.0,You can tell Juno is not even that upset that ...,1000.0,"“There’s no Rebecca without Keeley” god, my te...",2800.0,Hannah looking straight into Jason's eyes sayi...,1500.0,That was the shortest episode of Ted Lasso I h...,...,0,0,0,0,0,0,0,0,0,0
3,--4tfbSyYDE,１７の男ですが、JAMになっていいですか？,1500.0,ファイナルの2曲をこの制服でパフォーマンスしてくれるなんて。すごく嬉しいのに、すごく泣けてき...,474.0,木全が手の指のところにJAMって書いてるところほんと可愛いし、ほんと好きだわ,31.0,ゆるく踊ってるメンバーが多い中、蓮くんはずっとキレキレに踊ってて嬉しいし、カッコいい！！,4.0,このMVを見ると、切なくて、愛おしくて、JO1って素晴らしいってなる。,...,0,0,0,0,0,0,0,0,0,0
7,-024Swollbc,This man is great. He gives his daughter priva...,139.0,Jared seems like a great person. For sure gonn...,368.0,This is obviously more important than school,1300.0,"Man is a genius, going to get to write that of...",44.0,Me: wait its not Friday\n\nSeth: pulled a snea...,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37478,zzd4ydafGR0,'DESTINED 2 WIN' OUT NOW !! https://liltjay.ln...,13000.0,claim your “BEFORE A MILLION” ticket 🎫,2200.0,Lil Tjay don't miss.,52000.0,A message to the next generations: Don't let t...,2300.0,"I hope you pull through bro, i know this is a ...",...,0,0,0,0,0,0,0,0,0,0
37479,zziBybeSAtw,That 2nd Half from the Lakers truly shows how ...,202.0,Montrezl Harrell is going crazy with the rebou...,1500.0,The Lakers have such a good bench and good def...,199.0,"Dang man, I can't wait to see the fans back in...",15.0,The Lakers are such a solid team in every aspe...,...,0,0,0,0,0,0,0,0,0,0
37480,zzk09ESX7e0,"For anyone here, this song is NOT their farewe...",4700.0,You know what? People may not str3am some of t...,298.0,This song deserves justice. Cannot believe it ...,7.0,Best song falan,8.0,This song hits so different after watching the...,...,0,0,0,0,0,0,0,0,0,0
37481,zzmQEb0Em5I,Foi um prazer passar esta tarde com vocês deba...,3000.0,"Petição pro Escudero vir aqui mais vezes, pois...",224.0,"Castanhari, mitico e igão sendo engolidos, arg...",37.0,"Chifre é igual consórcio, uma hora você é cont...",1700.0,"ze graça parece ter estudado o convidado, muit...",...,0,0,0,0,0,0,0,0,0,0
37482,zzxPZwaA-8w,"If you didn't know Leicester is a good team, B...",203.0,"As a Chelsea fan, I have never said this, but ...",2200.0,It’s like watching the old Gareth bale playing...,1700.0,As a fan of Chelsea I say thank you to Tottenh...,715.0,Bale just single handedly destroyed Leicester....,...,0,0,0,0,0,0,0,0,0,0

In [32]:
import numpy as np

In [33]:
xvc = xvc.replace(np.nan, '', regex=True)

# Dividing data so processing in portions

In [37]:
xvc_1 = xvc[0:3000]
xvc_2 = xvc[3000:6000]
xvc_3 = xvc[6000:9000]
xvc_4 = xvc[9000:12000]
xvc_5 = xvc[12000:15000]
xvc_6 = xvc[15000:18000]
xvc_7 = xvc[18000:21000]
xvc_8 = xvc[21000:24000]
xvc_9 = xvc[24000:27000]
xvc_10 = xvc[27000:30000]
xvc_11 = xvc[30000:33000]
xvc_12 = xvc[33000:]

# Comment Rate

In [38]:
def add11(a):
    result = model(tokenizer.encode(a, return_tensors='pt', truncation=True, max_length=512))
    xt = int(torch.argmax(result.logits))+1
    return xt

In [39]:
from tqdm import tqdm
from time import sleep
 
 
for i in tqdm(range(1, 13), desc ="Progress: "):
    if(i==1):
        print(i, ' start')
        for j in range(1,21):
            ty = 'comment_{}_rate'.format(j)
            ty1 = ty[:-5]
            xvc_1[ty] = xvc_1.apply(lambda row : add11(row[ty1]), axis=1)
        xvc_1.to_csv('rating_comment_{}.csv'.format(i))
        print(i, ' end')
    elif(i==2):
        print(i, ' start')
        for j in range(1,21):
            ty = 'comment_{}_rate'.format(j)
            ty1 = ty[:-5]
            xvc_2[ty] = xvc_2.apply(lambda row : add11(row[ty1]), axis=1)
        xvc_2.to_csv('rating_comment_{}.csv'.format(i))
        print(i, ' end')
    elif(i==3):
        print(i, ' start')
        for j in range(1,21):
            ty = 'comment_{}_rate'.format(j)
            ty1 = ty[:-5]
            xvc_3[ty] = xvc_3.apply(lambda row : add11(row[ty1]), axis=1)
        xvc_3.to_csv('rating_comment_{}.csv'.format(i))
        print(i, ' end')
    elif(i==4):
        print(i, ' start')
        for j in range(1,21):
            ty = 'comment_{}_rate'.format(j)
            ty1 = ty[:-5]
            xvc_4[ty] = xvc_4.apply(lambda row : add11(row[ty1]), axis=1)
        xvc_4.to_csv('rating_comment_{}.csv'.format(i))
        print(i, ' end')
    elif(i==5):
        print(i, ' start')
        for j in range(1,21):
            ty = 'comment_{}_rate'.format(j)
            ty1 = ty[:-5]
            xvc_5[ty] = xvc_5.apply(lambda row : add11(row[ty1]), axis=1)
        xvc_5.to_csv('rating_comment_{}.csv'.format(i))
        print(i, ' end')
    elif(i==6):
        print(i, ' start')
        for j in range(1,21):
            ty = 'comment_{}_rate'.format(j)
            ty1 = ty[:-5]
            xvc_6[ty] = xvc_6.apply(lambda row : add11(row[ty1]), axis=1)
        xvc_6.to_csv('rating_comment_{}.csv'.format(i))
        print(i, ' end')
    elif(i==7):
        print(i, ' start')
        for j in range(1,21):
            ty = 'comment_{}_rate'.format(j)
            ty1 = ty[:-5]
            xvc_7[ty] = xvc_7.apply(lambda row : add11(row[ty1]), axis=1)
        xvc_7.to_csv('rating_comment_{}.csv'.format(i))
        print(i, ' end')
    elif(i==8):
        print(i, ' start')
        for j in range(1,21):
            ty = 'comment_{}_rate'.format(j)
            ty1 = ty[:-5]
            xvc_8[ty] = xvc_8.apply(lambda row : add11(row[ty1]), axis=1)
        xvc_8.to_csv('rating_comment_{}.csv'.format(i))
        print(i, ' end')
    elif(i==9):
        print(i, ' start')
        for j in range(1,21):
            ty = 'comment_{}_rate'.format(j)
            ty1 = ty[:-5]
            xvc_9[ty] = xvc_9.apply(lambda row : add11(row[ty1]), axis=1)
        xvc_9.to_csv('rating_comment_{}.csv'.format(i))
        print(i, ' end')
    elif(i==10):
        print(i, ' start')
        for j in range(1,21):
            ty = 'comment_{}_rate'.format(j)
            ty1 = ty[:-5]
            xvc_10[ty] = xvc_10.apply(lambda row : add11(row[ty1]), axis=1)
        xvc_10.to_csv('rating_comment_{}.csv'.format(i))
        print(i, ' end')
    elif(i==11):
        print(i, ' start')
        for j in range(1,21):
            ty = 'comment_{}_rate'.format(j)
            ty1 = ty[:-5]
            xvc_11[ty] = xvc_11.apply(lambda row : add11(row[ty1]), axis=1)
        xvc_11.to_csv('rating_comment_{}.csv'.format(i))
        print(i, ' end')
    elif(i==12):
        print(i, ' start')
        for j in range(1,21):
            ty = 'comment_{}_rate'.format(j)
            ty1 = ty[:-5]
            xvc_12[ty] = xvc_12.apply(lambda row : add11(row[ty1]), axis=1)
        xvc_12.to_csv('rating_comment_{}.csv'.format(i))
        print(i, ' end')

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Progress:   0%|                                          | 0/12 [00:00<?, ?it/s]

1  start

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_1[ty] = xvc_1.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_1[ty] = xvc_1.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_1[ty] = xvc_1.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_1[ty] = xvc_1.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_1[ty] = xvc_1.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_1[ty] = xvc_1.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_1[ty] = xvc_1.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_1[ty] = xvc_1.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_1[ty] = xvc_1.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_1[ty] = xvc_1.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_1[ty] = xvc_1.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_1[ty] = xvc_1.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_1[ty] = xvc_1.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_1[ty] = xvc_1.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_1[ty] = xvc_1.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_1[ty] = xvc_1.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_1[ty] = xvc_1.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_1[ty] = xvc_1.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_1[ty] = xvc_1.apply(lambda row : add11(row[ty1]), axis=1)

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_1[ty] = xvc_1.apply(lambda row : add11(row[ty1]), axis=1)
Progress:   8%|██▌                           | 1/12 [52:29<9:37:25, 3149.63s/it]

1  end
2  start

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_2[ty] = xvc_2.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_2[ty] = xvc_2.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_2[ty] = xvc_2.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_2[ty] = xvc_2.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_2[ty] = xvc_2.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_2[ty] = xvc_2.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_2[ty] = xvc_2.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_2[ty] = xvc_2.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_2[ty] = xvc_2.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_2[ty] = xvc_2.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_2[ty] = xvc_2.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_2[ty] = xvc_2.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_2[ty] = xvc_2.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_2[ty] = xvc_2.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_2[ty] = xvc_2.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_2[ty] = xvc_2.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_2[ty] = xvc_2.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_2[ty] = xvc_2.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_2[ty] = xvc_2.apply(lambda row : add11(row[ty1]), axis=1)

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_2[ty] = xvc_2.apply(lambda row : add11(row[ty1]), axis=1)
Progress:  17%|████▋                       | 2/12 [1:44:38<8:42:55, 3137.50s/it]

2  end
3  start

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_3[ty] = xvc_3.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_3[ty] = xvc_3.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_3[ty] = xvc_3.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_3[ty] = xvc_3.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_3[ty] = xvc_3.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_3[ty] = xvc_3.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_3[ty] = xvc_3.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_3[ty] = xvc_3.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_3[ty] = xvc_3.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_3[ty] = xvc_3.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_3[ty] = xvc_3.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_3[ty] = xvc_3.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_3[ty] = xvc_3.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_3[ty] = xvc_3.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_3[ty] = xvc_3.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_3[ty] = xvc_3.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_3[ty] = xvc_3.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_3[ty] = xvc_3.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_3[ty] = xvc_3.apply(lambda row : add11(row[ty1]), axis=1)

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_3[ty] = xvc_3.apply(lambda row : add11(row[ty1]), axis=1)
Progress:  25%|███████                     | 3/12 [2:37:56<7:54:45, 3165.04s/it]

3  end
4  start

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_4[ty] = xvc_4.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_4[ty] = xvc_4.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_4[ty] = xvc_4.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_4[ty] = xvc_4.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_4[ty] = xvc_4.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_4[ty] = xvc_4.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_4[ty] = xvc_4.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_4[ty] = xvc_4.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_4[ty] = xvc_4.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_4[ty] = xvc_4.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_4[ty] = xvc_4.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_4[ty] = xvc_4.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_4[ty] = xvc_4.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_4[ty] = xvc_4.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_4[ty] = xvc_4.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_4[ty] = xvc_4.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_4[ty] = xvc_4.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_4[ty] = xvc_4.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_4[ty] = xvc_4.apply(lambda row : add11(row[ty1]), axis=1)

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_4[ty] = xvc_4.apply(lambda row : add11(row[ty1]), axis=1)
Progress:  33%|█████████▎                  | 4/12 [3:29:50<6:59:17, 3144.72s/it]

4  end
5  start

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_5[ty] = xvc_5.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_5[ty] = xvc_5.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_5[ty] = xvc_5.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_5[ty] = xvc_5.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_5[ty] = xvc_5.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_5[ty] = xvc_5.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_5[ty] = xvc_5.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_5[ty] = xvc_5.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_5[ty] = xvc_5.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_5[ty] = xvc_5.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_5[ty] = xvc_5.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_5[ty] = xvc_5.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_5[ty] = xvc_5.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_5[ty] = xvc_5.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_5[ty] = xvc_5.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_5[ty] = xvc_5.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_5[ty] = xvc_5.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_5[ty] = xvc_5.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_5[ty] = xvc_5.apply(lambda row : add11(row[ty1]), axis=1)

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_5[ty] = xvc_5.apply(lambda row : add11(row[ty1]), axis=1)
Progress:  42%|███████████▋                | 5/12 [4:25:20<6:14:41, 3211.71s/it]

5  end
6  start

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_6[ty] = xvc_6.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_6[ty] = xvc_6.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_6[ty] = xvc_6.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_6[ty] = xvc_6.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_6[ty] = xvc_6.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_6[ty] = xvc_6.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_6[ty] = xvc_6.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_6[ty] = xvc_6.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_6[ty] = xvc_6.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_6[ty] = xvc_6.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_6[ty] = xvc_6.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_6[ty] = xvc_6.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_6[ty] = xvc_6.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_6[ty] = xvc_6.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_6[ty] = xvc_6.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_6[ty] = xvc_6.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_6[ty] = xvc_6.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_6[ty] = xvc_6.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_6[ty] = xvc_6.apply(lambda row : add11(row[ty1]), axis=1)

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_6[ty] = xvc_6.apply(lambda row : add11(row[ty1]), axis=1)
Progress:  50%|██████████████              | 6/12 [5:18:18<5:20:00, 3200.10s/it]

6  end
7  start

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_7[ty] = xvc_7.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_7[ty] = xvc_7.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_7[ty] = xvc_7.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_7[ty] = xvc_7.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_7[ty] = xvc_7.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_7[ty] = xvc_7.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_7[ty] = xvc_7.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_7[ty] = xvc_7.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_7[ty] = xvc_7.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_7[ty] = xvc_7.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_7[ty] = xvc_7.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_7[ty] = xvc_7.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_7[ty] = xvc_7.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_7[ty] = xvc_7.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_7[ty] = xvc_7.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_7[ty] = xvc_7.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_7[ty] = xvc_7.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_7[ty] = xvc_7.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_7[ty] = xvc_7.apply(lambda row : add11(row[ty1]), axis=1)

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_7[ty] = xvc_7.apply(lambda row : add11(row[ty1]), axis=1)
Progress:  58%|████████████████▎           | 7/12 [6:12:08<4:27:30, 3210.11s/it]

7  end
8  start

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_8[ty] = xvc_8.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_8[ty] = xvc_8.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_8[ty] = xvc_8.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_8[ty] = xvc_8.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_8[ty] = xvc_8.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_8[ty] = xvc_8.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_8[ty] = xvc_8.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_8[ty] = xvc_8.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_8[ty] = xvc_8.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_8[ty] = xvc_8.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_8[ty] = xvc_8.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_8[ty] = xvc_8.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_8[ty] = xvc_8.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_8[ty] = xvc_8.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_8[ty] = xvc_8.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_8[ty] = xvc_8.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_8[ty] = xvc_8.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_8[ty] = xvc_8.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_8[ty] = xvc_8.apply(lambda row : add11(row[ty1]), axis=1)

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_8[ty] = xvc_8.apply(lambda row : add11(row[ty1]), axis=1)
Progress:  67%|██████████████████▋         | 8/12 [7:04:23<3:32:24, 3186.14s/it]

8  end
9  start

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_9[ty] = xvc_9.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_9[ty] = xvc_9.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_9[ty] = xvc_9.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_9[ty] = xvc_9.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_9[ty] = xvc_9.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_9[ty] = xvc_9.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_9[ty] = xvc_9.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_9[ty] = xvc_9.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_9[ty] = xvc_9.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_9[ty] = xvc_9.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_9[ty] = xvc_9.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_9[ty] = xvc_9.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_9[ty] = xvc_9.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_9[ty] = xvc_9.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_9[ty] = xvc_9.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_9[ty] = xvc_9.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_9[ty] = xvc_9.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_9[ty] = xvc_9.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_9[ty] = xvc_9.apply(lambda row : add11(row[ty1]), axis=1)

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_9[ty] = xvc_9.apply(lambda row : add11(row[ty1]), axis=1)
Progress:  75%|█████████████████████       | 9/12 [7:53:59<2:36:01, 3120.50s/it]

9  end
10  start

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_10[ty] = xvc_10.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_10[ty] = xvc_10.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_10[ty] = xvc_10.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_10[ty] = xvc_10.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_10[ty] = xvc_10.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_10[ty] = xvc_10.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_10[ty] = xvc_10.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_10[ty] = xvc_10.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_10[ty] = xvc_10.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_10[ty] = xvc_10.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_10[ty] = xvc_10.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_10[ty] = xvc_10.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_10[ty] = xvc_10.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_10[ty] = xvc_10.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_10[ty] = xvc_10.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_10[ty] = xvc_10.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_10[ty] = xvc_10.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_10[ty] = xvc_10.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_10[ty] = xvc_10.apply(lambda row : add11(row[ty1]), axis=1)

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_10[ty] = xvc_10.apply(lambda row : add11(row[ty1]), axis=1)
Progress:  83%|██████████████████████▌    | 10/12 [8:41:27<1:41:12, 3036.15s/it]

10  end
11  start

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_11[ty] = xvc_11.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_11[ty] = xvc_11.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_11[ty] = xvc_11.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_11[ty] = xvc_11.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_11[ty] = xvc_11.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_11[ty] = xvc_11.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_11[ty] = xvc_11.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_11[ty] = xvc_11.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_11[ty] = xvc_11.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_11[ty] = xvc_11.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_11[ty] = xvc_11.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_11[ty] = xvc_11.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_11[ty] = xvc_11.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_11[ty] = xvc_11.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_11[ty] = xvc_11.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_11[ty] = xvc_11.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_11[ty] = xvc_11.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_11[ty] = xvc_11.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_11[ty] = xvc_11.apply(lambda row : add11(row[ty1]), axis=1)

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_11[ty] = xvc_11.apply(lambda row : add11(row[ty1]), axis=1)
Progress:  92%|██████████████████████████▌  | 11/12 [9:30:17<50:03, 3003.84s/it]

11  end
12  start

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_12[ty] = xvc_12.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_12[ty] = xvc_12.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_12[ty] = xvc_12.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_12[ty] = xvc_12.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_12[ty] = xvc_12.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_12[ty] = xvc_12.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_12[ty] = xvc_12.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_12[ty] = xvc_12.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_12[ty] = xvc_12.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_12[ty] = xvc_12.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_12[ty] = xvc_12.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_12[ty] = xvc_12.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_12[ty] = xvc_12.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_12[ty] = xvc_12.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_12[ty] = xvc_12.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_12[ty] = xvc_12.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_12[ty] = xvc_12.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_12[ty] = xvc_12.apply(lambda row : add11(row[ty1]), axis=1)
/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_12[ty] = xvc_12.apply(lambda row : add11(row[ty1]), axis=1)

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/1246651882.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xvc_12[ty] = xvc_12.apply(lambda row : add11(row[ty1]), axis=1)
Progress: 100%|████████████████████████████| 12/12 [10:35:24<00:00, 3177.03s/it]

12  end

In [40]:
xtr = pd.read_csv('rating_comment_12.csv')

In [41]:
xtr

,Unnamed: 0,video_id,comment_1,comment_1_likes,comment_2,comment_2_likes,comment_3,comment_3_likes,comment_4,comment_4_likes,...,comment_11_rate,comment_12_rate,comment_13_rate,comment_14_rate,comment_15_rate,comment_16_rate,comment_17_rate,comment_18_rate,comment_19_rate,comment_20_rate
0,33459,t1JNuMgKaSA,Hi Mat here: which car would you drive home? B...,4500.0,The reason they made the M4 so fast is so nobo...,3200.0,Lets all just be honest if you got any one of ...,2800.0,It’s crazy how M4 always struggles with tracti...,1200.0,...,5,3,4,5,4,5,5,1,1,4
1,33460,t1Jg9ksj8yk,Who is watching this may thier parents live 10...,321.0,Priti and akshada is doing 2 prank 🤣,16.0,Akshada-Cute😘\nPreeti-Smart😎\nSanket-Strong💪🏻\...,6.0,"😂😂😂 aap logone to meri manki bat janli, but ve...",3.0,...,4,3,5,5,5,5,5,5,5,5
2,33461,t1K7b9q8cYs,Cyber-ops is ONLINE!,2100.0,So happy to see that they got Simon Pegg on bo...,50.0,I'm starting to feel like Ashens should just s...,86.0,"The short trailer feels very professional, if ...",410.0,...,2,5,5,4,5,1,3,5,4,4
3,33462,t1Ps2qCbKrQ,What are your thoughts on game 2?! 👇,575.0,The level is already so high 😳,2900.0,Omg that was a nice defense by Chris Pierre,790.0,"Nick skates flat ground so effortlessly, he’s ...",135.0,...,5,1,1,1,5,4,5,5,5,3
4,33463,t1fqh_gmcDU,DJ Khaled gone put together the Avengers of Ja...,4200.0,None but Chills and Goosebumps! \nI'm not a Ja...,75.0,Literally an insane achievement. This is histo...,385.0,Thank you Jamaica for blessing these Mexican e...,246.0,...,5,1,5,5,5,5,5,5,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4019,37478,zzd4ydafGR0,'DESTINED 2 WIN' OUT NOW !! https://liltjay.ln...,13000.0,claim your “BEFORE A MILLION” ticket 🎫,2200.0,Lil Tjay don't miss.,52000.0,A message to the next generations: Don't let t...,2300.0,...,5,4,1,1,3,5,5,1,5,5
4020,37479,zziBybeSAtw,That 2nd Half from the Lakers truly shows how ...,202.0,Montrezl Harrell is going crazy with the rebou...,1500.0,The Lakers have such a good bench and good def...,199.0,"Dang man, I can't wait to see the fans back in...",15.0,...,5,5,5,1,5,5,4,1,2,5
4021,37480,zzk09ESX7e0,"For anyone here, this song is NOT their farewe...",4700.0,You know what? People may not str3am some of t...,298.0,This song deserves justice. Cannot believe it ...,7.0,Best song falan,8.0,...,5,5,5,5,5,4,5,4,5,5
4022,37481,zzmQEb0Em5I,Foi um prazer passar esta tarde com vocês deba...,3000.0,"Petição pro Escudero vir aqui mais vezes, pois...",224.0,"Castanhari, mitico e igão sendo engolidos, arg...",37.0,"Chifre é igual consórcio, uma hora você é cont...",1700.0,...,2,3,3,5,5,2,2,5,1,2
4023,37482,zzxPZwaA-8w,"If you didn't know Leicester is a good team, B...",203.0,"As a Chelsea fan, I have never said this, but ...",2200.0,It’s like watching the old Gareth bale playing...,1700.0,As a fan of Chelsea I say thank you to Tottenh...,715.0,...,5,2,3,5,5,3,4,1,5,5

# Concatenating all different portions

In [42]:
vc = pd.concat([xvc_1, xvc_2, xvc_3, xvc_4, xvc_5, xvc_6, xvc_7, xvc_8, xvc_9, xvc_10, xvc_11, xvc_12], axis=0)

In [43]:
vc

,video_id,comment_1,comment_1_likes,comment_2,comment_2_likes,comment_3,comment_3_likes,comment_4,comment_4_likes,comment_5,...,comment_11_rate,comment_12_rate,comment_13_rate,comment_14_rate,comment_15_rate,comment_16_rate,comment_17_rate,comment_18_rate,comment_19_rate,comment_20_rate
0,--0bCF-iK2E,Can’t wait for him to kiss the badge in front ...,2100.0,"Respect to Dortmund fans,must be sad losing him.",1800.0,One of the most talented players Bundesliga ha...,40.0,It's so heartbreaking look at Sancho playing f...,12.0,wish him well in manchester united,...,3,5,5,5,5,5,5,5,5,5
1,--14w5SOEUs,RIP Takeoff. The world is gonna miss you and y...,982.0,I love how Migos knows every assignment and to...,3.0,This video just puts a smile on my face 😂,0.0,It’s been about 48 hrs since Takeoff’s passing...,438.0,The amount of swag these 3 possess is unmatche...,...,5,5,5,5,5,5,5,5,5,5
2,--40TEbZ9Is,"I get that she isn't a nobody, but to see some...",1100.0,You can tell Juno is not even that upset that ...,1000.0,"“There’s no Rebecca without Keeley” god, my te...",2800.0,Hannah looking straight into Jason's eyes sayi...,1500.0,That was the shortest episode of Ted Lasso I h...,...,5,5,5,5,5,5,5,5,5,5
3,--4tfbSyYDE,１７の男ですが、JAMになっていいですか？,1500.0,ファイナルの2曲をこの制服でパフォーマンスしてくれるなんて。すごく嬉しいのに、すごく泣けてき...,474.0,木全が手の指のところにJAMって書いてるところほんと可愛いし、ほんと好きだわ,31.0,ゆるく踊ってるメンバーが多い中、蓮くんはずっとキレキレに踊ってて嬉しいし、カッコいい！！,4.0,このMVを見ると、切なくて、愛おしくて、JO1って素晴らしいってなる。,...,5,5,1,5,1,5,5,5,3,5
7,-024Swollbc,This man is great. He gives his daughter priva...,139.0,Jared seems like a great person. For sure gonn...,368.0,This is obviously more important than school,1300.0,"Man is a genius, going to get to write that of...",44.0,Me: wait its not Friday\n\nSeth: pulled a snea...,...,5,5,5,5,5,5,1,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37478,zzd4ydafGR0,'DESTINED 2 WIN' OUT NOW !! https://liltjay.ln...,13000.0,claim your “BEFORE A MILLION” ticket 🎫,2200.0,Lil Tjay don't miss.,52000.0,A message to the next generations: Don't let t...,2300.0,"I hope you pull through bro, i know this is a ...",...,5,4,1,1,3,5,5,1,5,5
37479,zziBybeSAtw,That 2nd Half from the Lakers truly shows how ...,202.0,Montrezl Harrell is going crazy with the rebou...,1500.0,The Lakers have such a good bench and good def...,199.0,"Dang man, I can't wait to see the fans back in...",15.0,The Lakers are such a solid team in every aspe...,...,5,5,5,1,5,5,4,1,2,5
37480,zzk09ESX7e0,"For anyone here, this song is NOT their farewe...",4700.0,You know what? People may not str3am some of t...,298.0,This song deserves justice. Cannot believe it ...,7.0,Best song falan,8.0,This song hits so different after watching the...,...,5,5,5,5,5,4,5,4,5,5
37481,zzmQEb0Em5I,Foi um prazer passar esta tarde com vocês deba...,3000.0,"Petição pro Escudero vir aqui mais vezes, pois...",224.0,"Castanhari, mitico e igão sendo engolidos, arg...",37.0,"Chifre é igual consórcio, uma hora você é cont...",1700.0,"ze graça parece ter estudado o convidado, muit...",...,2,3,3,5,5,2,2,5,1,2
37482,zzxPZwaA-8w,"If you didn't know Leicester is a good team, B...",203.0,"As a Chelsea fan, I have never said this, but ...",2200.0,It’s like watching the old Gareth bale playing...,1700.0,As a fan of Chelsea I say thank you to Tottenh...,715.0,Bale just single handedly destroyed Leicester....,...,5,2,3,5,5,3,4,1,5,5

In [44]:
vc = vc.replace(np.nan, '', regex=True)

In [45]:
# xvc = pd.merge(xvc, xvc1, on="video_id")

In [47]:
vc.loc[vc['comment_1_likes'] == '']

,video_id,comment_1,comment_1_likes,comment_2,comment_2_likes,comment_3,comment_3_likes,comment_4,comment_4_likes,comment_5,...,comment_11_rate,comment_12_rate,comment_13_rate,comment_14_rate,comment_15_rate,comment_16_rate,comment_17_rate,comment_18_rate,comment_19_rate,comment_20_rate
46,-4_QqWMIsnE,,,,,,,,,,...,4,4,4,4,4,4,4,4,4,4
47,-4n2JbVeJGM,,,,,,,,,,...,4,4,4,4,4,4,4,4,4,4
84,-9QpaOmJqVg,,,,,,,,,,...,4,4,4,4,4,4,4,4,4,4
91,-9sAAgkZ5Sg,,,,,,,,,,...,4,4,4,4,4,4,4,4,4,4
491,-rh4sVOOk-c,,,,,,,,,,...,4,4,4,4,4,4,4,4,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37392,zq4eBwOxFe0,,,,,,,,,,...,4,4,4,4,4,4,4,4,4,4
37396,zqJoSH_VxF4,,,,,,,,,,...,4,4,4,4,4,4,4,4,4,4
37422,ztN6PfChdTE,,,,,,,,,,...,4,4,4,4,4,4,4,4,4,4
37452,zxLytVs3klI,,,,,,,,,,...,4,4,4,4,4,4,4,4,4,4
37467,zyQQ20cHTqc,,,,,,,,,,...,4,4,4,4,4,4,4,4,4,4

In [65]:
vc = vc.reset_index()

In [66]:
vc

,level_0,index,video_id,comment_1,comment_1_likes,comment_2,comment_2_likes,comment_3,comment_3_likes,comment_4,...,comment_11_rate,comment_12_rate,comment_13_rate,comment_14_rate,comment_15_rate,comment_16_rate,comment_17_rate,comment_18_rate,comment_19_rate,comment_20_rate
0,0,0,--0bCF-iK2E,Can’t wait for him to kiss the badge in front ...,2100,"Respect to Dortmund fans,must be sad losing him.",1800,One of the most talented players Bundesliga ha...,40,It's so heartbreaking look at Sancho playing f...,...,3,5,5,5,5,5,5,5,5,5
1,1,1,--14w5SOEUs,RIP Takeoff. The world is gonna miss you and y...,982,I love how Migos knows every assignment and to...,3,This video just puts a smile on my face 😂,0,It’s been about 48 hrs since Takeoff’s passing...,...,5,5,5,5,5,5,5,5,5,5
2,2,2,--40TEbZ9Is,"I get that she isn't a nobody, but to see some...",1100,You can tell Juno is not even that upset that ...,1000,"“There’s no Rebecca without Keeley” god, my te...",2800,Hannah looking straight into Jason's eyes sayi...,...,5,5,5,5,5,5,5,5,5,5
3,3,3,--4tfbSyYDE,１７の男ですが、JAMになっていいですか？,1500,ファイナルの2曲をこの制服でパフォーマンスしてくれるなんて。すごく嬉しいのに、すごく泣けてき...,474,木全が手の指のところにJAMって書いてるところほんと可愛いし、ほんと好きだわ,31,ゆるく踊ってるメンバーが多い中、蓮くんはずっとキレキレに踊ってて嬉しいし、カッコいい！！,...,5,5,1,5,1,5,5,5,3,5
4,4,7,-024Swollbc,This man is great. He gives his daughter priva...,139,Jared seems like a great person. For sure gonn...,368,This is obviously more important than school,1300,"Man is a genius, going to get to write that of...",...,5,5,5,5,5,5,1,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37018,37019,37478,zzd4ydafGR0,'DESTINED 2 WIN' OUT NOW !! https://liltjay.ln...,13000.0,claim your “BEFORE A MILLION” ticket 🎫,2200.0,Lil Tjay don't miss.,52000.0,A message to the next generations: Don't let t...,...,5,4,1,1,3,5,5,1,5,5
37019,37020,37479,zziBybeSAtw,That 2nd Half from the Lakers truly shows how ...,202.0,Montrezl Harrell is going crazy with the rebou...,1500.0,The Lakers have such a good bench and good def...,199.0,"Dang man, I can't wait to see the fans back in...",...,5,5,5,1,5,5,4,1,2,5
37020,37021,37480,zzk09ESX7e0,"For anyone here, this song is NOT their farewe...",4700.0,You know what? People may not str3am some of t...,298.0,This song deserves justice. Cannot believe it ...,7.0,Best song falan,...,5,5,5,5,5,4,5,4,5,5
37021,37022,37481,zzmQEb0Em5I,Foi um prazer passar esta tarde com vocês deba...,3000.0,"Petição pro Escudero vir aqui mais vezes, pois...",224.0,"Castanhari, mitico e igão sendo engolidos, arg...",37.0,"Chifre é igual consórcio, uma hora você é cont...",...,2,3,3,5,5,2,2,5,1,2
37022,37023,37482,zzxPZwaA-8w,"If you didn't know Leicester is a good team, B...",203.0,"As a Chelsea fan, I have never said this, but ...",2200.0,It’s like watching the old Gareth bale playing...,1700.0,As a fan of Chelsea I say thank you to Tottenh...,...,5,2,3,5,5,3,4,1,5,5

In [51]:
# comment likes can't be empty strings so replacing that with 0 if no comment likes
for i in range(0,37024):
    for j in range(1,21):
        if(vc['comment_{}_likes'.format(j)][i]==""):
            vc['comment_{}_likes'.format(j)][i]=0
#         else:
#             vc['comment_{}_likes'.format(j)][i] = int(vc['comment_{}_likes'.format(j)][i])

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/4108910662.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vc['comment_{}_likes'.format(j)][i]=0

In [52]:
vc

,index,video_id,comment_1,comment_1_likes,comment_2,comment_2_likes,comment_3,comment_3_likes,comment_4,comment_4_likes,...,comment_11_rate,comment_12_rate,comment_13_rate,comment_14_rate,comment_15_rate,comment_16_rate,comment_17_rate,comment_18_rate,comment_19_rate,comment_20_rate
0,0,--0bCF-iK2E,Can’t wait for him to kiss the badge in front ...,2100,"Respect to Dortmund fans,must be sad losing him.",1800,One of the most talented players Bundesliga ha...,40,It's so heartbreaking look at Sancho playing f...,12,...,3,5,5,5,5,5,5,5,5,5
1,1,--14w5SOEUs,RIP Takeoff. The world is gonna miss you and y...,982,I love how Migos knows every assignment and to...,3,This video just puts a smile on my face 😂,0,It’s been about 48 hrs since Takeoff’s passing...,438,...,5,5,5,5,5,5,5,5,5,5
2,2,--40TEbZ9Is,"I get that she isn't a nobody, but to see some...",1100,You can tell Juno is not even that upset that ...,1000,"“There’s no Rebecca without Keeley” god, my te...",2800,Hannah looking straight into Jason's eyes sayi...,1500,...,5,5,5,5,5,5,5,5,5,5
3,3,--4tfbSyYDE,１７の男ですが、JAMになっていいですか？,1500,ファイナルの2曲をこの制服でパフォーマンスしてくれるなんて。すごく嬉しいのに、すごく泣けてき...,474,木全が手の指のところにJAMって書いてるところほんと可愛いし、ほんと好きだわ,31,ゆるく踊ってるメンバーが多い中、蓮くんはずっとキレキレに踊ってて嬉しいし、カッコいい！！,4,...,5,5,1,5,1,5,5,5,3,5
4,7,-024Swollbc,This man is great. He gives his daughter priva...,139,Jared seems like a great person. For sure gonn...,368,This is obviously more important than school,1300,"Man is a genius, going to get to write that of...",44,...,5,5,5,5,5,5,1,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37019,37478,zzd4ydafGR0,'DESTINED 2 WIN' OUT NOW !! https://liltjay.ln...,13000.0,claim your “BEFORE A MILLION” ticket 🎫,2200.0,Lil Tjay don't miss.,52000.0,A message to the next generations: Don't let t...,2300.0,...,5,4,1,1,3,5,5,1,5,5
37020,37479,zziBybeSAtw,That 2nd Half from the Lakers truly shows how ...,202.0,Montrezl Harrell is going crazy with the rebou...,1500.0,The Lakers have such a good bench and good def...,199.0,"Dang man, I can't wait to see the fans back in...",15.0,...,5,5,5,1,5,5,4,1,2,5
37021,37480,zzk09ESX7e0,"For anyone here, this song is NOT their farewe...",4700.0,You know what? People may not str3am some of t...,298.0,This song deserves justice. Cannot believe it ...,7.0,Best song falan,8.0,...,5,5,5,5,5,4,5,4,5,5
37022,37481,zzmQEb0Em5I,Foi um prazer passar esta tarde com vocês deba...,3000.0,"Petição pro Escudero vir aqui mais vezes, pois...",224.0,"Castanhari, mitico e igão sendo engolidos, arg...",37.0,"Chifre é igual consórcio, uma hora você é cont...",1700.0,...,2,3,3,5,5,2,2,5,1,2
37023,37482,zzxPZwaA-8w,"If you didn't know Leicester is a good team, B...",203.0,"As a Chelsea fan, I have never said this, but ...",2200.0,It’s like watching the old Gareth bale playing...,1700.0,As a fan of Chelsea I say thank you to Tottenh...,715.0,...,5,2,3,5,5,3,4,1,5,5

In [57]:
vc.loc[vc['comment_1_likes'] ==  'I would like to let you know that you have been accepted into Hogwarts school of witchcraft and wizardry']

,index,video_id,comment_1,comment_1_likes,comment_2,comment_2_likes,comment_3,comment_3_likes,comment_4,comment_4_likes,...,comment_11_rate,comment_12_rate,comment_13_rate,comment_14_rate,comment_15_rate,comment_16_rate,comment_17_rate,comment_18_rate,comment_19_rate,comment_20_rate
2340,2799,last year. What was your favorite trick?,4900,I would like to let you know that you have bee...,143,This man is a legend,4400,"As a Potterhead, I approve of this in every wa...",363,"If this guy was a teacher at Hogwarts, he'd be...",...,4,4,5,5,4,1,1,4,4,4

In [63]:
vc[2335:2345]

,index,video_id,comment_1,comment_1_likes,comment_2,comment_2_likes,comment_3,comment_3_likes,comment_4,comment_4_likes,...,comment_11_rate,comment_12_rate,comment_13_rate,comment_14_rate,comment_15_rate,comment_16_rate,comment_17_rate,comment_18_rate,comment_19_rate,comment_20_rate
2335,2794,3fcKrF1VzOA,Can we get this comment to “it’s the top comme...,153,Being very generous with these scores this sea...,128,Who agrees that the vlogs gets better every se...,243,On The Road episodes from non league clubs are...,51,...,5,5,5,5,5,5,5,5,1,5
2336,2795,3feMrqs8uJY,"Massive, MASSIVE respect to Daniel Bryan for m...",1100,Jay Uso’s heel turn is just going to further e...,2000,"Now Jey a heel, they are family, if you can't ...",2200,Paul Heyman: what do I get paid to do\nVince: ...,1800,...,5,1,5,4,5,4,5,5,1,4
2337,2796,3fnKV6A9ZS8,George is one obedient son. He seems the type ...,1500,"Charlotte is hilarious, George & Louis seem qu...",1300,"George grows so fast, I still remember his fir...",60,"I love and respect this lovely family so much,...",33,...,5,4,5,5,5,5,5,5,4,5
2338,2797,3g1ZEXOCKAs,OLE IN!!! Give him a 10 year Alan Pardew contr...,627,1:34:35 first goal\n1:44:53 second goal\n2:58:...,1400,The new AFTV by far much more entertaining th...,5,First goal: AWB back post\nSecond goal: Shaw b...,118,...,1,5,4,4,4,4,4,4,4,4
2339,2798,3gJ4cBdUkPo,Excited to finally post this video! We filmed ...,0,,0,,0,,0,...,4,4,4,4,4,4,4,4,4,4
2341,2800,3gJjYjIGGME,白米だって言ってありがたさを噛み締めているところをお茶漬けにしちゃうあたり共感しかない,1100,笑顔の裏の努力が凄い,3000,可愛い\nかっこいー\n色気\n\n3拍子そろった殿方やな,3300,お茶碗準備してるのに結局釜戸から直で行くの好きすぎるな…,234,...,5,3,5,3,5,5,5,5,5,5
2342,2801,3gaYCDlbpig,No se que puedo decir... Uno de los videos/can...,2600,"""La espera no es un enemigo, en ella aprendo q...",497,I lost my wife almost 8 months ago to CJD. It...,6,LETRA en ESPAÑOL:\n\nVerso 1:\nDios soy yo otr...,830,...,5,5,5,5,5,5,5,5,1,5
2343,2802,3ghhxb5txPg,i swear if i see one more comment saying ‘he’s...,2300,There's a unique vibe with Ruel that u can't j...,4100,His music is such a viiiibe. He doesn’t have o...,3800,ruel's music needs to be heard by everyone,746,...,5,5,5,5,5,4,5,5,5,5
2344,2803,3gmCdjhhCN8,"If you guys enjoy, make sure you're SUBSCRIBED...",27000,Never seen JJ this humble in my life💀,10000,"Vikk getting revenge and still being nice, if ...",18000,KSI: has knowledge written on his body\n\nAlso...,8000,...,3,1,3,2,2,4,5,1,5,5
2345,2804,3gmoZ4qe064,Where the real young ma fans at 🤔🤔🤔,1900,She hit us with her entire soul. We need more ...,468,"🔥🔥🔥This isn't just a song, she's speaking her ...",154,This song brings me to tears everytime. I may...,2,...,5,5,5,5,5,5,1,5,4,5

In [60]:
vc.index[2340]

2340

In [61]:
vc = vc.drop(vc.index[2340])

In [62]:
vc

,index,video_id,comment_1,comment_1_likes,comment_2,comment_2_likes,comment_3,comment_3_likes,comment_4,comment_4_likes,...,comment_11_rate,comment_12_rate,comment_13_rate,comment_14_rate,comment_15_rate,comment_16_rate,comment_17_rate,comment_18_rate,comment_19_rate,comment_20_rate
0,0,--0bCF-iK2E,Can’t wait for him to kiss the badge in front ...,2100,"Respect to Dortmund fans,must be sad losing him.",1800,One of the most talented players Bundesliga ha...,40,It's so heartbreaking look at Sancho playing f...,12,...,3,5,5,5,5,5,5,5,5,5
1,1,--14w5SOEUs,RIP Takeoff. The world is gonna miss you and y...,982,I love how Migos knows every assignment and to...,3,This video just puts a smile on my face 😂,0,It’s been about 48 hrs since Takeoff’s passing...,438,...,5,5,5,5,5,5,5,5,5,5
2,2,--40TEbZ9Is,"I get that she isn't a nobody, but to see some...",1100,You can tell Juno is not even that upset that ...,1000,"“There’s no Rebecca without Keeley” god, my te...",2800,Hannah looking straight into Jason's eyes sayi...,1500,...,5,5,5,5,5,5,5,5,5,5
3,3,--4tfbSyYDE,１７の男ですが、JAMになっていいですか？,1500,ファイナルの2曲をこの制服でパフォーマンスしてくれるなんて。すごく嬉しいのに、すごく泣けてき...,474,木全が手の指のところにJAMって書いてるところほんと可愛いし、ほんと好きだわ,31,ゆるく踊ってるメンバーが多い中、蓮くんはずっとキレキレに踊ってて嬉しいし、カッコいい！！,4,...,5,5,1,5,1,5,5,5,3,5
4,7,-024Swollbc,This man is great. He gives his daughter priva...,139,Jared seems like a great person. For sure gonn...,368,This is obviously more important than school,1300,"Man is a genius, going to get to write that of...",44,...,5,5,5,5,5,5,1,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37019,37478,zzd4ydafGR0,'DESTINED 2 WIN' OUT NOW !! https://liltjay.ln...,13000.0,claim your “BEFORE A MILLION” ticket 🎫,2200.0,Lil Tjay don't miss.,52000.0,A message to the next generations: Don't let t...,2300.0,...,5,4,1,1,3,5,5,1,5,5
37020,37479,zziBybeSAtw,That 2nd Half from the Lakers truly shows how ...,202.0,Montrezl Harrell is going crazy with the rebou...,1500.0,The Lakers have such a good bench and good def...,199.0,"Dang man, I can't wait to see the fans back in...",15.0,...,5,5,5,1,5,5,4,1,2,5
37021,37480,zzk09ESX7e0,"For anyone here, this song is NOT their farewe...",4700.0,You know what? People may not str3am some of t...,298.0,This song deserves justice. Cannot believe it ...,7.0,Best song falan,8.0,...,5,5,5,5,5,4,5,4,5,5
37022,37481,zzmQEb0Em5I,Foi um prazer passar esta tarde com vocês deba...,3000.0,"Petição pro Escudero vir aqui mais vezes, pois...",224.0,"Castanhari, mitico e igão sendo engolidos, arg...",37.0,"Chifre é igual consórcio, uma hora você é cont...",1700.0,...,2,3,3,5,5,2,2,5,1,2
37023,37482,zzxPZwaA-8w,"If you didn't know Leicester is a good team, B...",203.0,"As a Chelsea fan, I have never said this, but ...",2200.0,It’s like watching the old Gareth bale playing...,1700.0,As a fan of Chelsea I say thank you to Tottenh...,715.0,...,5,2,3,5,5,3,4,1,5,5

In [68]:
vc

,level_0,index,video_id,comment_1,comment_1_likes,comment_2,comment_2_likes,comment_3,comment_3_likes,comment_4,...,comment_11_rate,comment_12_rate,comment_13_rate,comment_14_rate,comment_15_rate,comment_16_rate,comment_17_rate,comment_18_rate,comment_19_rate,comment_20_rate
0,0,0,--0bCF-iK2E,Can’t wait for him to kiss the badge in front ...,2100,"Respect to Dortmund fans,must be sad losing him.",1800,One of the most talented players Bundesliga ha...,40,It's so heartbreaking look at Sancho playing f...,...,3,5,5,5,5,5,5,5,5,5
1,1,1,--14w5SOEUs,RIP Takeoff. The world is gonna miss you and y...,982,I love how Migos knows every assignment and to...,3,This video just puts a smile on my face 😂,0,It’s been about 48 hrs since Takeoff’s passing...,...,5,5,5,5,5,5,5,5,5,5
2,2,2,--40TEbZ9Is,"I get that she isn't a nobody, but to see some...",1100,You can tell Juno is not even that upset that ...,1000,"“There’s no Rebecca without Keeley” god, my te...",2800,Hannah looking straight into Jason's eyes sayi...,...,5,5,5,5,5,5,5,5,5,5
3,3,3,--4tfbSyYDE,１７の男ですが、JAMになっていいですか？,1500,ファイナルの2曲をこの制服でパフォーマンスしてくれるなんて。すごく嬉しいのに、すごく泣けてき...,474,木全が手の指のところにJAMって書いてるところほんと可愛いし、ほんと好きだわ,31,ゆるく踊ってるメンバーが多い中、蓮くんはずっとキレキレに踊ってて嬉しいし、カッコいい！！,...,5,5,1,5,1,5,5,5,3,5
4,4,7,-024Swollbc,This man is great. He gives his daughter priva...,139,Jared seems like a great person. For sure gonn...,368,This is obviously more important than school,1300,"Man is a genius, going to get to write that of...",...,5,5,5,5,5,5,1,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37018,37019,37478,zzd4ydafGR0,'DESTINED 2 WIN' OUT NOW !! https://liltjay.ln...,13000.0,claim your “BEFORE A MILLION” ticket 🎫,2200.0,Lil Tjay don't miss.,52000.0,A message to the next generations: Don't let t...,...,5,4,1,1,3,5,5,1,5,5
37019,37020,37479,zziBybeSAtw,That 2nd Half from the Lakers truly shows how ...,202.0,Montrezl Harrell is going crazy with the rebou...,1500.0,The Lakers have such a good bench and good def...,199.0,"Dang man, I can't wait to see the fans back in...",...,5,5,5,1,5,5,4,1,2,5
37020,37021,37480,zzk09ESX7e0,"For anyone here, this song is NOT their farewe...",4700.0,You know what? People may not str3am some of t...,298.0,This song deserves justice. Cannot believe it ...,7.0,Best song falan,...,5,5,5,5,5,4,5,4,5,5
37021,37022,37481,zzmQEb0Em5I,Foi um prazer passar esta tarde com vocês deba...,3000.0,"Petição pro Escudero vir aqui mais vezes, pois...",224.0,"Castanhari, mitico e igão sendo engolidos, arg...",37.0,"Chifre é igual consórcio, uma hora você é cont...",...,2,3,3,5,5,2,2,5,1,2
37022,37023,37482,zzxPZwaA-8w,"If you didn't know Leicester is a good team, B...",203.0,"As a Chelsea fan, I have never said this, but ...",2200.0,It’s like watching the old Gareth bale playing...,1700.0,As a fan of Chelsea I say thank you to Tottenh...,...,5,2,3,5,5,3,4,1,5,5

In [69]:
vc = vc.drop(columns="index")
vc = vc.drop(columns="level_0")

In [70]:
vc

,video_id,comment_1,comment_1_likes,comment_2,comment_2_likes,comment_3,comment_3_likes,comment_4,comment_4_likes,comment_5,...,comment_11_rate,comment_12_rate,comment_13_rate,comment_14_rate,comment_15_rate,comment_16_rate,comment_17_rate,comment_18_rate,comment_19_rate,comment_20_rate
0,--0bCF-iK2E,Can’t wait for him to kiss the badge in front ...,2100,"Respect to Dortmund fans,must be sad losing him.",1800,One of the most talented players Bundesliga ha...,40,It's so heartbreaking look at Sancho playing f...,12,wish him well in manchester united,...,3,5,5,5,5,5,5,5,5,5
1,--14w5SOEUs,RIP Takeoff. The world is gonna miss you and y...,982,I love how Migos knows every assignment and to...,3,This video just puts a smile on my face 😂,0,It’s been about 48 hrs since Takeoff’s passing...,438,The amount of swag these 3 possess is unmatche...,...,5,5,5,5,5,5,5,5,5,5
2,--40TEbZ9Is,"I get that she isn't a nobody, but to see some...",1100,You can tell Juno is not even that upset that ...,1000,"“There’s no Rebecca without Keeley” god, my te...",2800,Hannah looking straight into Jason's eyes sayi...,1500,That was the shortest episode of Ted Lasso I h...,...,5,5,5,5,5,5,5,5,5,5
3,--4tfbSyYDE,１７の男ですが、JAMになっていいですか？,1500,ファイナルの2曲をこの制服でパフォーマンスしてくれるなんて。すごく嬉しいのに、すごく泣けてき...,474,木全が手の指のところにJAMって書いてるところほんと可愛いし、ほんと好きだわ,31,ゆるく踊ってるメンバーが多い中、蓮くんはずっとキレキレに踊ってて嬉しいし、カッコいい！！,4,このMVを見ると、切なくて、愛おしくて、JO1って素晴らしいってなる。,...,5,5,1,5,1,5,5,5,3,5
4,-024Swollbc,This man is great. He gives his daughter priva...,139,Jared seems like a great person. For sure gonn...,368,This is obviously more important than school,1300,"Man is a genius, going to get to write that of...",44,Me: wait its not Friday\n\nSeth: pulled a snea...,...,5,5,5,5,5,5,1,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37018,zzd4ydafGR0,'DESTINED 2 WIN' OUT NOW !! https://liltjay.ln...,13000.0,claim your “BEFORE A MILLION” ticket 🎫,2200.0,Lil Tjay don't miss.,52000.0,A message to the next generations: Don't let t...,2300.0,"I hope you pull through bro, i know this is a ...",...,5,4,1,1,3,5,5,1,5,5
37019,zziBybeSAtw,That 2nd Half from the Lakers truly shows how ...,202.0,Montrezl Harrell is going crazy with the rebou...,1500.0,The Lakers have such a good bench and good def...,199.0,"Dang man, I can't wait to see the fans back in...",15.0,The Lakers are such a solid team in every aspe...,...,5,5,5,1,5,5,4,1,2,5
37020,zzk09ESX7e0,"For anyone here, this song is NOT their farewe...",4700.0,You know what? People may not str3am some of t...,298.0,This song deserves justice. Cannot believe it ...,7.0,Best song falan,8.0,This song hits so different after watching the...,...,5,5,5,5,5,4,5,4,5,5
37021,zzmQEb0Em5I,Foi um prazer passar esta tarde com vocês deba...,3000.0,"Petição pro Escudero vir aqui mais vezes, pois...",224.0,"Castanhari, mitico e igão sendo engolidos, arg...",37.0,"Chifre é igual consórcio, uma hora você é cont...",1700.0,"ze graça parece ter estudado o convidado, muit...",...,2,3,3,5,5,2,2,5,1,2
37022,zzxPZwaA-8w,"If you didn't know Leicester is a good team, B...",203.0,"As a Chelsea fan, I have never said this, but ...",2200.0,It’s like watching the old Gareth bale playing...,1700.0,As a fan of Chelsea I say thank you to Tottenh...,715.0,Bale just single handedly destroyed Leicester....,...,5,2,3,5,5,3,4,1,5,5

In [71]:
vc.to_csv('rate_comment_like.csv')

In [74]:
# orignal data with other parameters for video like view_count, ...
cv = pd.read_csv('data_with_rating.csv')

In [75]:
cv

,Unnamed: 0,video_id,view_count,likes,comment_count,dislikes,comments_rate,comment_1,comment_2,comment_3,...,comment_11,comment_12,comment_13,comment_14,comment_15,comment_16,comment_17,comment_18,comment_19,comment_20
0,0,--0bCF-iK2E,1048888,19515,1319,226,4,wish him well in manchester united,"Respect to Dortmund fans,must be sad losing him.",It's so heartbreaking look at Sancho playing f...,...,The amount of opportunities he creates is ridi...,He was beast at dortmund hope in United he wil...,This was a nice tribute by the Bundesliga to S...,I'm dying for him to rediscover this form for ...,here after his first Man United goal. What a p...,Thank you for your service to Dortmund Jaden S...,He is forever a joy to watch. I wish you all t...,Saw him play for England the other day for fir...,"His arrival excites me, fans of Borussia Dortm...",Shockingly calm and collective in the box\nFan...
1,1,--14w5SOEUs,15352638,359277,18729,7479,5,RIP Takeoff. The world is gonna miss you and y...,It’s been about 48 hrs since Takeoff’s passing...,The amount of swag these 3 possess is unmatche...,...,"20,30 and 40 years from now, this gonna be one...",Words can't describe how tragic his death is o...,"I'm 43 years old, and I've enjoyed the evoluti...",The way Migos flow on this track is just incre...,All 3 Changed the Game of Rap \nThere Will nev...,"Migos was so fresh, so fly. Undoubtedly, one ...","Out of Migos entire catalog, this is sincerely...","I have heard several Migos songs, I LISTENED t...",This is exactly why Migos need to be appreciat...,Wow!!! This is hip hop. I am from the East Coa...
2,2,--40TEbZ9Is,925281,11212,831,401,5,"I get that she isn't a nobody, but to see some...",You can tell Juno is not even that upset that ...,"“There’s no Rebecca without Keeley” god, my te...",...,"For those who may not know, Hannah Waddingham’...","For years she was theatres best kept secret, n...",The chemistry they have on and off screen make...,"Her blonde hair, hair do, skin tone, toned arm...",You can tell how grateful she is and how happy...,I feel like she really didn’t expect this and ...,Her acceptance speech is what put me over the ...,This is the kind of speech we love. genuine fu...,Best speech of the night! Hannah seems like su...,I nearly cried when I saw Jason's face. so muc...
3,3,--4tfbSyYDE,2641597,39131,3745,441,4,１７の男ですが、JAMになっていいですか？,この1年間、日本の音楽番組に出られなくてすごく虚しい思いもしたけど、今思えば、デビューしてい...,この制服姿を見ると、祥生がC→Bにランクアップしたのに「蓮くんに申し訳ない…」と泣いている姿...,...,私はデビューしてからJO1を知ったんですが、蓮くんに投票してくださった全ての人に感謝致します。,メンバーが肩の力を抜いて過去曲を披露するのは解釈変わってすごく良いなあ〜,ほんとに、、、蓮くん、、\nどこまで魅力的なの、、,皆さんのコメント読んでまた涙が出てきます。\n今でもJO1verを見ながら優心、しゅんや、本...,やっぱYoungって神曲だ、、、。,YOUNGの蓮くんもものすごく良くて定期的に見に来てしまう,なんで木全歌う時ポーカーフェイスなのに歌って移動する時いつもニコニコしてんのかわいいwwww...,蓮くん、1O1のときyoung踊ってたのもあるのかもしれないけど、すごい楽しそうに踊ってるの...,I never worry about life lifeのところの蓮君の声がすごく好きです！,ファイナルの2曲をこの制服でパフォーマンスしてくれるなんて。すごく嬉しいのに、すごく泣けてき...
4,4,-024Swollbc,271736,16622,743,90,4,This man is great. He gives his daughter priva...,Jared seems like a great person. For sure gonn...,This is obviously more important than school,...,Awesome! great to see the community of MTBers ...,Your doing so many good things Seth keep up th...,"Man Seth, you’re going to be an incredible dad!",You deserve so much more support your amazing,Picked up a couple scx24 for myself and son. W...,Thanks so much Seth. Bogue Chitto is my local ...,Couldn’t have gone to a better dude. I’m so st...,Straight up love the community outreach progra...,you got me into mountain biking and i am lovin...,"Hi Seth, I was impatiently waiting for your vi..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36958,36958,zzd4ydafGR0,120408275,2180780,81360,35871,4,'DESTINED 2 WIN' OUT NOW !! https://liltjay.ln...,ayo who’s single for valentine’s day coz dis ...,Lil Tjay don't miss.,...,"As long as there's music like this, there's st...",I'm not a fan of him but I wish him a speedy r...,"An artist with a beautiful heart, man we can’t...",Calling My Phone Finally Out ! 🔥🔥\nThank ya’ll...,Pull thru tjay 🙏 we can’t lose you man we love...,"can’t lose another legend man, keep fighting t...","Dont die on us Tjay, I know this is a hard tim...",We can’t loose you Tjay.We need you back more ...,Essa música marcou uma fase da minha vida e te...,"Lil Tjay doesn’t know this, but he’s making ma..."
36959,36959,zziBybeSAtw,2841917,20759,2624,1049,4,Montrezl Harrell is going crazy with the rebou...,That 2nd Half from the Lakers truly shows how ...,The Lakers are such a solid team in every aspe...,...,Harrell was a great addition to the Lakers. He...,the way the lakers are playing right now is ve...,LeBron aging like a fine wine.. 🔥🔥🔥,Our chemistry is out of this World!\n\nFuckin'...,Lakers are very strong and they’re playing as ...,What a game by Lakers! Appreciate much the bal...,"Montrezl is ballin out there, what a differenc...",Another great effort by ALL the Lakers. Great ...,Bruh I could see Lebron dominating even if its...,Great team effort tonight! 6 Lakers finished i...
36960,36960,zzk09ESX7e0,13346678,720854,90616,4426,4,"For anyone here, this song is NOT their farewe...",You know what? People may not str3am some of t...,I'm tearing up omg 2-3 years ago I thought I w...,...,Come back here after watching the documentary....,I'm here after hearing they have a comeback so...,MAMAMOO \nun grupo que vino a revolucionar el ...,Kpop has some absolutely fabulous vocal talent...,"Reinas vocales, gracias Mamamoo por introducir...",I know I'm not the only one who came back here...,Podemos decir que esta cancion es tan especial...,Moomoos keep str3aming :\n\nWAWN 13M ➡️ 14M\nE...,Best voices in the industry.\nBest women group...,What I love about Mamamoo is that they don't n...
36961,36961,zzmQEb0Em5I,252057,19198,1471,1234,3,Foi um prazer passar esta tarde com vocês deba...,"Petição pro Escudero vir aqui mais vezes, pois...",FELIPE CASTANHARI - Podpah #03: Os caras xinga...,...,"Escudero me convenceu da sua verdade , indepen...","Mano, imagina o Igão chegar no estúdio na hr q...","Mano, esse Lord é o melhor hahahaha dei muita ...","O escudeiro é muito bala, ele tem convicção da...",Mano o escudeiro não precisa dormir com cobert...,De longe o Escudero é o mais profissional em m...,Pega a argumentação do Escudero e compara com ...,Gostaria de agradecer ao canal por tão bela en...,Curto muito o trabalho do Escudero.,"Cara, sendo contemporâneo do Lordão, compartil..."
36962,36962,zzxPZwaA-8w,2252090,34063,2004,868,4,Bale ended Leicester's dream in 7 mins,It’s like watching the old Gareth bale playing...,"As a Chelsea fan, I have never said this, but ...",...,"God bless Kane, Son and Bale!",Jose is Chelsea legend forever\nHe brought in ...,"When the title is long and dramatic, you know ...",I never thought I’ll ever say these but From a...,"1:22 Good to see SON, KANE, BALE teamwork toge...",4th goal:\nGoal : Bale\nAssist : Bale 😅,Thanks Gareth for your contribution this seaso...,"“BALE!”, I can’t explain how I felt watching t...",Thank you gareth bale!\nFrom a chelsea fan,great way to end what's been a horrible season...

In [76]:
for i in range(1,21):
    cv = cv.drop(columns="comment_{}".format(i))

In [77]:
cv

,Unnamed: 0,video_id,view_count,likes,comment_count,dislikes,comments_rate
0,0,--0bCF-iK2E,1048888,19515,1319,226,4
1,1,--14w5SOEUs,15352638,359277,18729,7479,5
2,2,--40TEbZ9Is,925281,11212,831,401,5
3,3,--4tfbSyYDE,2641597,39131,3745,441,4
4,4,-024Swollbc,271736,16622,743,90,4
...,...,...,...,...,...,...,...
36958,36958,zzd4ydafGR0,120408275,2180780,81360,35871,4
36959,36959,zziBybeSAtw,2841917,20759,2624,1049,4
36960,36960,zzk09ESX7e0,13346678,720854,90616,4426,4
36961,36961,zzmQEb0Em5I,252057,19198,1471,1234,3
36962,36962,zzxPZwaA-8w,2252090,34063,2004,868,4

In [78]:
cv = cv.drop(columns="Unnamed: 0".format(i))
cv = cv.drop(columns="comments_rate".format(i))

In [79]:
cv

          video_id  view_count    likes  comment_count  dislikes
0      --0bCF-iK2E     1048888    19515           1319       226
1      --14w5SOEUs    15352638   359277          18729      7479
2      --40TEbZ9Is      925281    11212            831       401
3      --4tfbSyYDE     2641597    39131           3745       441
4      -024Swollbc      271736    16622            743        90
...            ...         ...      ...            ...       ...
36958  zzd4ydafGR0   120408275  2180780          81360     35871
36959  zziBybeSAtw     2841917    20759           2624      1049
36960  zzk09ESX7e0    13346678   720854          90616      4426
36961  zzmQEb0Em5I      252057    19198           1471      1234
36962  zzxPZwaA-8w     2252090    34063           2004       868

[36963 rows x 5 columns]

# Merging tables with same video_id

In [80]:
vc = pd.merge(vc, cv, on="video_id")

In [81]:
vc

,video_id,comment_1,comment_1_likes,comment_2,comment_2_likes,comment_3,comment_3_likes,comment_4,comment_4_likes,comment_5,...,comment_15_rate,comment_16_rate,comment_17_rate,comment_18_rate,comment_19_rate,comment_20_rate,view_count,likes,comment_count,dislikes
0,--0bCF-iK2E,Can’t wait for him to kiss the badge in front ...,2100,"Respect to Dortmund fans,must be sad losing him.",1800,One of the most talented players Bundesliga ha...,40,It's so heartbreaking look at Sancho playing f...,12,wish him well in manchester united,...,5,5,5,5,5,5,1048888,19515,1319,226
1,--14w5SOEUs,RIP Takeoff. The world is gonna miss you and y...,982,I love how Migos knows every assignment and to...,3,This video just puts a smile on my face 😂,0,It’s been about 48 hrs since Takeoff’s passing...,438,The amount of swag these 3 possess is unmatche...,...,5,5,5,5,5,5,15352638,359277,18729,7479
2,--40TEbZ9Is,"I get that she isn't a nobody, but to see some...",1100,You can tell Juno is not even that upset that ...,1000,"“There’s no Rebecca without Keeley” god, my te...",2800,Hannah looking straight into Jason's eyes sayi...,1500,That was the shortest episode of Ted Lasso I h...,...,5,5,5,5,5,5,925281,11212,831,401
3,--4tfbSyYDE,１７の男ですが、JAMになっていいですか？,1500,ファイナルの2曲をこの制服でパフォーマンスしてくれるなんて。すごく嬉しいのに、すごく泣けてき...,474,木全が手の指のところにJAMって書いてるところほんと可愛いし、ほんと好きだわ,31,ゆるく踊ってるメンバーが多い中、蓮くんはずっとキレキレに踊ってて嬉しいし、カッコいい！！,4,このMVを見ると、切なくて、愛おしくて、JO1って素晴らしいってなる。,...,1,5,5,5,3,5,2641597,39131,3745,441
4,-024Swollbc,This man is great. He gives his daughter priva...,139,Jared seems like a great person. For sure gonn...,368,This is obviously more important than school,1300,"Man is a genius, going to get to write that of...",44,Me: wait its not Friday\n\nSeth: pulled a snea...,...,5,5,1,5,5,5,271736,16622,743,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36958,zzd4ydafGR0,'DESTINED 2 WIN' OUT NOW !! https://liltjay.ln...,13000.0,claim your “BEFORE A MILLION” ticket 🎫,2200.0,Lil Tjay don't miss.,52000.0,A message to the next generations: Don't let t...,2300.0,"I hope you pull through bro, i know this is a ...",...,3,5,5,1,5,5,120408275,2180780,81360,35871
36959,zziBybeSAtw,That 2nd Half from the Lakers truly shows how ...,202.0,Montrezl Harrell is going crazy with the rebou...,1500.0,The Lakers have such a good bench and good def...,199.0,"Dang man, I can't wait to see the fans back in...",15.0,The Lakers are such a solid team in every aspe...,...,5,5,4,1,2,5,2841917,20759,2624,1049
36960,zzk09ESX7e0,"For anyone here, this song is NOT their farewe...",4700.0,You know what? People may not str3am some of t...,298.0,This song deserves justice. Cannot believe it ...,7.0,Best song falan,8.0,This song hits so different after watching the...,...,5,4,5,4,5,5,13346678,720854,90616,4426
36961,zzmQEb0Em5I,Foi um prazer passar esta tarde com vocês deba...,3000.0,"Petição pro Escudero vir aqui mais vezes, pois...",224.0,"Castanhari, mitico e igão sendo engolidos, arg...",37.0,"Chifre é igual consórcio, uma hora você é cont...",1700.0,"ze graça parece ter estudado o convidado, muit...",...,5,2,2,5,1,2,252057,19198,1471,1234
36962,zzxPZwaA-8w,"If you didn't know Leicester is a good team, B...",203.0,"As a Chelsea fan, I have never said this, but ...",2200.0,It’s like watching the old Gareth bale playing...,1700.0,As a fan of Chelsea I say thank you to Tottenh...,715.0,Bale just single handedly destroyed Leicester....,...,5,3,4,1,5,5,2252090,34063,2004,868

In [82]:
for i in range(0,36963):
    for j in range(1,21):
        vc['comment_{}_likes'.format(j)][i] = int(vc['comment_{}_likes'.format(j)][i])

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/2307447752.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vc['comment_{}_likes'.format(j)][i] = int(vc['comment_{}_likes'.format(j)][i])

In [83]:
vc

,video_id,comment_1,comment_1_likes,comment_2,comment_2_likes,comment_3,comment_3_likes,comment_4,comment_4_likes,comment_5,...,comment_15_rate,comment_16_rate,comment_17_rate,comment_18_rate,comment_19_rate,comment_20_rate,view_count,likes,comment_count,dislikes
0,--0bCF-iK2E,Can’t wait for him to kiss the badge in front ...,2100,"Respect to Dortmund fans,must be sad losing him.",1800,One of the most talented players Bundesliga ha...,40,It's so heartbreaking look at Sancho playing f...,12,wish him well in manchester united,...,5,5,5,5,5,5,1048888,19515,1319,226
1,--14w5SOEUs,RIP Takeoff. The world is gonna miss you and y...,982,I love how Migos knows every assignment and to...,3,This video just puts a smile on my face 😂,0,It’s been about 48 hrs since Takeoff’s passing...,438,The amount of swag these 3 possess is unmatche...,...,5,5,5,5,5,5,15352638,359277,18729,7479
2,--40TEbZ9Is,"I get that she isn't a nobody, but to see some...",1100,You can tell Juno is not even that upset that ...,1000,"“There’s no Rebecca without Keeley” god, my te...",2800,Hannah looking straight into Jason's eyes sayi...,1500,That was the shortest episode of Ted Lasso I h...,...,5,5,5,5,5,5,925281,11212,831,401
3,--4tfbSyYDE,１７の男ですが、JAMになっていいですか？,1500,ファイナルの2曲をこの制服でパフォーマンスしてくれるなんて。すごく嬉しいのに、すごく泣けてき...,474,木全が手の指のところにJAMって書いてるところほんと可愛いし、ほんと好きだわ,31,ゆるく踊ってるメンバーが多い中、蓮くんはずっとキレキレに踊ってて嬉しいし、カッコいい！！,4,このMVを見ると、切なくて、愛おしくて、JO1って素晴らしいってなる。,...,1,5,5,5,3,5,2641597,39131,3745,441
4,-024Swollbc,This man is great. He gives his daughter priva...,139,Jared seems like a great person. For sure gonn...,368,This is obviously more important than school,1300,"Man is a genius, going to get to write that of...",44,Me: wait its not Friday\n\nSeth: pulled a snea...,...,5,5,1,5,5,5,271736,16622,743,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36958,zzd4ydafGR0,'DESTINED 2 WIN' OUT NOW !! https://liltjay.ln...,13000,claim your “BEFORE A MILLION” ticket 🎫,2200,Lil Tjay don't miss.,52000,A message to the next generations: Don't let t...,2300,"I hope you pull through bro, i know this is a ...",...,3,5,5,1,5,5,120408275,2180780,81360,35871
36959,zziBybeSAtw,That 2nd Half from the Lakers truly shows how ...,202,Montrezl Harrell is going crazy with the rebou...,1500,The Lakers have such a good bench and good def...,199,"Dang man, I can't wait to see the fans back in...",15,The Lakers are such a solid team in every aspe...,...,5,5,4,1,2,5,2841917,20759,2624,1049
36960,zzk09ESX7e0,"For anyone here, this song is NOT their farewe...",4700,You know what? People may not str3am some of t...,298,This song deserves justice. Cannot believe it ...,7,Best song falan,8,This song hits so different after watching the...,...,5,4,5,4,5,5,13346678,720854,90616,4426
36961,zzmQEb0Em5I,Foi um prazer passar esta tarde com vocês deba...,3000,"Petição pro Escudero vir aqui mais vezes, pois...",224,"Castanhari, mitico e igão sendo engolidos, arg...",37,"Chifre é igual consórcio, uma hora você é cont...",1700,"ze graça parece ter estudado o convidado, muit...",...,5,2,2,5,1,2,252057,19198,1471,1234
36962,zzxPZwaA-8w,"If you didn't know Leicester is a good team, B...",203,"As a Chelsea fan, I have never said this, but ...",2200,It’s like watching the old Gareth bale playing...,1700,As a fan of Chelsea I say thank you to Tottenh...,715,Bale just single handedly destroyed Leicester....,...,5,3,4,1,5,5,2252090,34063,2004,868

In [84]:
vc.to_csv("final_data.csv")

In [86]:
# for i in range(0,36963):
for j in range(1,21):
    yy = "comment_{}".format(j)
    vc = vc.drop(columns=yy)

In [87]:
vc

,video_id,comment_1_likes,comment_2_likes,comment_3_likes,comment_4_likes,comment_5_likes,comment_6_likes,comment_7_likes,comment_8_likes,comment_9_likes,...,comment_15_rate,comment_16_rate,comment_17_rate,comment_18_rate,comment_19_rate,comment_20_rate,view_count,likes,comment_count,dislikes
0,--0bCF-iK2E,2100,1800,40,12,2500,587,37,66,33,...,5,5,5,5,5,5,1048888,19515,1319,226
1,--14w5SOEUs,982,3,0,438,1100,342,2000,687,152,...,5,5,5,5,5,5,15352638,359277,18729,7479
2,--40TEbZ9Is,1100,1000,2800,1500,2000,1100,1100,544,300,...,5,5,5,5,5,5,925281,11212,831,401
3,--4tfbSyYDE,1500,474,31,4,41,163,123,211,31,...,1,5,5,5,3,5,2641597,39131,3745,441
4,-024Swollbc,139,368,1300,44,788,15,1,106,2,...,5,5,1,5,5,5,271736,16622,743,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36958,zzd4ydafGR0,13000,2200,52000,2300,1500,267,1200,112,1400,...,3,5,5,1,5,5,120408275,2180780,81360,35871
36959,zziBybeSAtw,202,1500,199,15,253,9,323,676,102,...,5,5,4,1,2,5,2841917,20759,2624,1049
36960,zzk09ESX7e0,4700,298,7,8,110,83,4200,93,174,...,5,4,5,4,5,5,13346678,720854,90616,4426
36961,zzmQEb0Em5I,3000,224,37,1700,223,794,13,132,2,...,5,2,2,5,1,2,252057,19198,1471,1234
36962,zzxPZwaA-8w,203,2200,1700,715,199,84,1300,382,40,...,5,3,4,1,5,5,2252090,34063,2004,868

In [88]:
vc.to_csv("final_data_1.csv")

In [89]:
vc = vc.drop(columns="video_id")

In [90]:
vc.columns

Index(['comment_1_likes', 'comment_2_likes', 'comment_3_likes',
       'comment_4_likes', 'comment_5_likes', 'comment_6_likes',
       'comment_7_likes', 'comment_8_likes', 'comment_9_likes',
       'comment_10_likes', 'comment_11_likes', 'comment_12_likes',
       'comment_13_likes', 'comment_14_likes', 'comment_15_likes',
       'comment_16_likes', 'comment_17_likes', 'comment_18_likes',
       'comment_19_likes', 'comment_20_likes', 'comment_1_rate',
       'comment_2_rate', 'comment_3_rate', 'comment_4_rate', 'comment_5_rate',
       'comment_6_rate', 'comment_7_rate', 'comment_8_rate', 'comment_9_rate',
       'comment_10_rate', 'comment_11_rate', 'comment_12_rate',
       'comment_13_rate', 'comment_14_rate', 'comment_15_rate',
       'comment_16_rate', 'comment_17_rate', 'comment_18_rate',
       'comment_19_rate', 'comment_20_rate', 'view_count', 'likes',
       'comment_count', 'dislikes'],
      dtype='object')

In [95]:
vc['comment_rate'] = 0

In [96]:
vc

,comment_1_likes,comment_2_likes,comment_3_likes,comment_4_likes,comment_5_likes,comment_6_likes,comment_7_likes,comment_8_likes,comment_9_likes,comment_10_likes,...,comment_16_rate,comment_17_rate,comment_18_rate,comment_19_rate,comment_20_rate,view_count,likes,comment_count,dislikes,comment_rate
0,2100,1800,40,12,2500,587,37,66,33,2,...,5,5,5,5,5,1048888,19515,1319,226,0
1,982,3,0,438,1100,342,2000,687,152,37,...,5,5,5,5,5,15352638,359277,18729,7479,0
2,1100,1000,2800,1500,2000,1100,1100,544,300,284,...,5,5,5,5,5,925281,11212,831,401,0
3,1500,474,31,4,41,163,123,211,31,11,...,5,5,5,3,5,2641597,39131,3745,441,0
4,139,368,1300,44,788,15,1,106,2,92,...,5,1,5,5,5,271736,16622,743,90,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36958,13000,2200,52000,2300,1500,267,1200,112,1400,595,...,5,5,1,5,5,120408275,2180780,81360,35871,0
36959,202,1500,199,15,253,9,323,676,102,6,...,5,4,1,2,5,2841917,20759,2624,1049,0
36960,4700,298,7,8,110,83,4200,93,174,7,...,4,5,4,5,5,13346678,720854,90616,4426,0
36961,3000,224,37,1700,223,794,13,132,2,348,...,2,2,5,1,2,252057,19198,1471,1234,0
36962,203,2200,1700,715,199,84,1300,382,40,141,...,3,4,1,5,5,2252090,34063,2004,868,0

In [97]:
for i in range(0, 36963):
    xr = 0
    for j in range(1,21):
        xr+=vc['comment_{}_rate'.format(j)][i]
    vc['comment_rate'][i]=xr

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/2683119295.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vc['comment_rate'][i]=xr

In [98]:
vc

,comment_1_likes,comment_2_likes,comment_3_likes,comment_4_likes,comment_5_likes,comment_6_likes,comment_7_likes,comment_8_likes,comment_9_likes,comment_10_likes,...,comment_16_rate,comment_17_rate,comment_18_rate,comment_19_rate,comment_20_rate,view_count,likes,comment_count,dislikes,comment_rate
0,2100,1800,40,12,2500,587,37,66,33,2,...,5,5,5,5,5,1048888,19515,1319,226,89
1,982,3,0,438,1100,342,2000,687,152,37,...,5,5,5,5,5,15352638,359277,18729,7479,96
2,1100,1000,2800,1500,2000,1100,1100,544,300,284,...,5,5,5,5,5,925281,11212,831,401,96
3,1500,474,31,4,41,163,123,211,31,11,...,5,5,5,3,5,2641597,39131,3745,441,86
4,139,368,1300,44,788,15,1,106,2,92,...,5,1,5,5,5,271736,16622,743,90,76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36958,13000,2200,52000,2300,1500,267,1200,112,1400,595,...,5,5,1,5,5,120408275,2180780,81360,35871,67
36959,202,1500,199,15,253,9,323,676,102,6,...,5,4,1,2,5,2841917,20759,2624,1049,84
36960,4700,298,7,8,110,83,4200,93,174,7,...,4,5,4,5,5,13346678,720854,90616,4426,92
36961,3000,224,37,1700,223,794,13,132,2,348,...,2,2,5,1,2,252057,19198,1471,1234,65
36962,203,2200,1700,715,199,84,1300,382,40,141,...,3,4,1,5,5,2252090,34063,2004,868,81

In [102]:
for i in range(0, 36963):
    vc['comment_rate'][i]=round(vc['comment_rate'][i]/20)

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/3018324840.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vc['comment_rate'][i]=round(vc['comment_rate'][i]/20)

In [103]:
vc

,comment_1_likes,comment_2_likes,comment_3_likes,comment_4_likes,comment_5_likes,comment_6_likes,comment_7_likes,comment_8_likes,comment_9_likes,comment_10_likes,...,comment_16_rate,comment_17_rate,comment_18_rate,comment_19_rate,comment_20_rate,view_count,likes,comment_count,dislikes,comment_rate
0,2100,1800,40,12,2500,587,37,66,33,2,...,5,5,5,5,5,1048888,19515,1319,226,4
1,982,3,0,438,1100,342,2000,687,152,37,...,5,5,5,5,5,15352638,359277,18729,7479,5
2,1100,1000,2800,1500,2000,1100,1100,544,300,284,...,5,5,5,5,5,925281,11212,831,401,5
3,1500,474,31,4,41,163,123,211,31,11,...,5,5,5,3,5,2641597,39131,3745,441,4
4,139,368,1300,44,788,15,1,106,2,92,...,5,1,5,5,5,271736,16622,743,90,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36958,13000,2200,52000,2300,1500,267,1200,112,1400,595,...,5,5,1,5,5,120408275,2180780,81360,35871,3
36959,202,1500,199,15,253,9,323,676,102,6,...,5,4,1,2,5,2841917,20759,2624,1049,4
36960,4700,298,7,8,110,83,4200,93,174,7,...,4,5,4,5,5,13346678,720854,90616,4426,5
36961,3000,224,37,1700,223,794,13,132,2,348,...,2,2,5,1,2,252057,19198,1471,1234,3
36962,203,2200,1700,715,199,84,1300,382,40,141,...,3,4,1,5,5,2252090,34063,2004,868,4

In [109]:
vc1 = vc.copy()

In [113]:
for j in range(1,21):
    vc1 = vc1.drop(columns="comment_{}_rate".format(j))

In [114]:
vc1

,comment_1_likes,comment_2_likes,comment_3_likes,comment_4_likes,comment_5_likes,comment_6_likes,comment_7_likes,comment_8_likes,comment_9_likes,comment_10_likes,...,comment_16_likes,comment_17_likes,comment_18_likes,comment_19_likes,comment_20_likes,view_count,likes,comment_count,dislikes,comment_rate
0,2100,1800,40,12,2500,587,37,66,33,2,...,2,0,0,38,1,1048888,19515,1319,226,4
1,982,3,0,438,1100,342,2000,687,152,37,...,36,47,95,156,29,15352638,359277,18729,7479,5
2,1100,1000,2800,1500,2000,1100,1100,544,300,284,...,436,44,34,151,233,925281,11212,831,401,5
3,1500,474,31,4,41,163,123,211,31,11,...,30,25,15,42,279,2641597,39131,3745,441,4
4,139,368,1300,44,788,15,1,106,2,92,...,0,0,1,1,42,271736,16622,743,90,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36958,13000,2200,52000,2300,1500,267,1200,112,1400,595,...,20,239,94,4,896,120408275,2180780,81360,35871,3
36959,202,1500,199,15,253,9,323,676,102,6,...,0,1000,3,91,10,2841917,20759,2624,1049,4
36960,4700,298,7,8,110,83,4200,93,174,7,...,56,5,34,17000,32,13346678,720854,90616,4426,5
36961,3000,224,37,1700,223,794,13,132,2,348,...,0,3,3,23,190,252057,19198,1471,1234,3
36962,203,2200,1700,715,199,84,1300,382,40,141,...,93,310,69,559,7,2252090,34063,2004,868,4

In [108]:
vc

,comment_1_likes,comment_2_likes,comment_3_likes,comment_4_likes,comment_5_likes,comment_6_likes,comment_7_likes,comment_8_likes,comment_9_likes,comment_10_likes,...,comment_16_rate,comment_17_rate,comment_18_rate,comment_19_rate,comment_20_rate,view_count,likes,comment_count,dislikes,comment_rate
0,2100,1800,40,12,2500,587,37,66,33,2,...,5,5,5,5,5,1048888,19515,1319,226,4
1,982,3,0,438,1100,342,2000,687,152,37,...,5,5,5,5,5,15352638,359277,18729,7479,5
2,1100,1000,2800,1500,2000,1100,1100,544,300,284,...,5,5,5,5,5,925281,11212,831,401,5
3,1500,474,31,4,41,163,123,211,31,11,...,5,5,5,3,5,2641597,39131,3745,441,4
4,139,368,1300,44,788,15,1,106,2,92,...,5,1,5,5,5,271736,16622,743,90,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36958,13000,2200,52000,2300,1500,267,1200,112,1400,595,...,5,5,1,5,5,120408275,2180780,81360,35871,3
36959,202,1500,199,15,253,9,323,676,102,6,...,5,4,1,2,5,2841917,20759,2624,1049,4
36960,4700,298,7,8,110,83,4200,93,174,7,...,4,5,4,5,5,13346678,720854,90616,4426,5
36961,3000,224,37,1700,223,794,13,132,2,348,...,2,2,5,1,2,252057,19198,1471,1234,3
36962,203,2200,1700,715,199,84,1300,382,40,141,...,3,4,1,5,5,2252090,34063,2004,868,4

In [115]:
vc2 = vc1.copy()

In [116]:
vc2

,comment_1_likes,comment_2_likes,comment_3_likes,comment_4_likes,comment_5_likes,comment_6_likes,comment_7_likes,comment_8_likes,comment_9_likes,comment_10_likes,...,comment_16_likes,comment_17_likes,comment_18_likes,comment_19_likes,comment_20_likes,view_count,likes,comment_count,dislikes,comment_rate
0,2100,1800,40,12,2500,587,37,66,33,2,...,2,0,0,38,1,1048888,19515,1319,226,4
1,982,3,0,438,1100,342,2000,687,152,37,...,36,47,95,156,29,15352638,359277,18729,7479,5
2,1100,1000,2800,1500,2000,1100,1100,544,300,284,...,436,44,34,151,233,925281,11212,831,401,5
3,1500,474,31,4,41,163,123,211,31,11,...,30,25,15,42,279,2641597,39131,3745,441,4
4,139,368,1300,44,788,15,1,106,2,92,...,0,0,1,1,42,271736,16622,743,90,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36958,13000,2200,52000,2300,1500,267,1200,112,1400,595,...,20,239,94,4,896,120408275,2180780,81360,35871,3
36959,202,1500,199,15,253,9,323,676,102,6,...,0,1000,3,91,10,2841917,20759,2624,1049,4
36960,4700,298,7,8,110,83,4200,93,174,7,...,56,5,34,17000,32,13346678,720854,90616,4426,5
36961,3000,224,37,1700,223,794,13,132,2,348,...,0,3,3,23,190,252057,19198,1471,1234,3
36962,203,2200,1700,715,199,84,1300,382,40,141,...,93,310,69,559,7,2252090,34063,2004,868,4

In [117]:
for j in range(1,21):
    vc2 = vc2.drop(columns="comment_{}_likes".format(j))

In [118]:
vc2

       view_count    likes  comment_count  dislikes  comment_rate
0         1048888    19515           1319       226             4
1        15352638   359277          18729      7479             5
2          925281    11212            831       401             5
3         2641597    39131           3745       441             4
4          271736    16622            743        90             4
...           ...      ...            ...       ...           ...
36958   120408275  2180780          81360     35871             3
36959     2841917    20759           2624      1049             4
36960    13346678   720854          90616      4426             5
36961      252057    19198           1471      1234             3
36962     2252090    34063           2004       868             4

[36963 rows x 5 columns]

In [119]:
vc

,comment_1_likes,comment_2_likes,comment_3_likes,comment_4_likes,comment_5_likes,comment_6_likes,comment_7_likes,comment_8_likes,comment_9_likes,comment_10_likes,...,comment_16_rate,comment_17_rate,comment_18_rate,comment_19_rate,comment_20_rate,view_count,likes,comment_count,dislikes,comment_rate
0,2100,1800,40,12,2500,587,37,66,33,2,...,5,5,5,5,5,1048888,19515,1319,226,4
1,982,3,0,438,1100,342,2000,687,152,37,...,5,5,5,5,5,15352638,359277,18729,7479,5
2,1100,1000,2800,1500,2000,1100,1100,544,300,284,...,5,5,5,5,5,925281,11212,831,401,5
3,1500,474,31,4,41,163,123,211,31,11,...,5,5,5,3,5,2641597,39131,3745,441,4
4,139,368,1300,44,788,15,1,106,2,92,...,5,1,5,5,5,271736,16622,743,90,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36958,13000,2200,52000,2300,1500,267,1200,112,1400,595,...,5,5,1,5,5,120408275,2180780,81360,35871,3
36959,202,1500,199,15,253,9,323,676,102,6,...,5,4,1,2,5,2841917,20759,2624,1049,4
36960,4700,298,7,8,110,83,4200,93,174,7,...,4,5,4,5,5,13346678,720854,90616,4426,5
36961,3000,224,37,1700,223,794,13,132,2,348,...,2,2,5,1,2,252057,19198,1471,1234,3
36962,203,2200,1700,715,199,84,1300,382,40,141,...,3,4,1,5,5,2252090,34063,2004,868,4

In [120]:
for i in range(1,21):
    vc['comment_{}_n'.format(i)]=0

In [121]:
vc

,comment_1_likes,comment_2_likes,comment_3_likes,comment_4_likes,comment_5_likes,comment_6_likes,comment_7_likes,comment_8_likes,comment_9_likes,comment_10_likes,...,comment_11_n,comment_12_n,comment_13_n,comment_14_n,comment_15_n,comment_16_n,comment_17_n,comment_18_n,comment_19_n,comment_20_n
0,2100,1800,40,12,2500,587,37,66,33,2,...,0,0,0,0,0,0,0,0,0,0
1,982,3,0,438,1100,342,2000,687,152,37,...,0,0,0,0,0,0,0,0,0,0
2,1100,1000,2800,1500,2000,1100,1100,544,300,284,...,0,0,0,0,0,0,0,0,0,0
3,1500,474,31,4,41,163,123,211,31,11,...,0,0,0,0,0,0,0,0,0,0
4,139,368,1300,44,788,15,1,106,2,92,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36958,13000,2200,52000,2300,1500,267,1200,112,1400,595,...,0,0,0,0,0,0,0,0,0,0
36959,202,1500,199,15,253,9,323,676,102,6,...,0,0,0,0,0,0,0,0,0,0
36960,4700,298,7,8,110,83,4200,93,174,7,...,0,0,0,0,0,0,0,0,0,0
36961,3000,224,37,1700,223,794,13,132,2,348,...,0,0,0,0,0,0,0,0,0,0
36962,203,2200,1700,715,199,84,1300,382,40,141,...,0,0,0,0,0,0,0,0,0,0

# Normalizing likes for each comment for a video_id

In [125]:
for i in range(0,36963):
    mi=2500000
    ma=-1
    for j in range(1,21):
        if(vc['comment_{}_likes'.format(j)][i] > ma):
            ma = vc['comment_{}_likes'.format(j)][i]
        if(vc['comment_{}_likes'.format(j)][i] < mi):
            mi = vc['comment_{}_likes'.format(j)][i]
    for j in range(1,21):
        if(ma == mi):
            vc['comment_{}_n'.format(j)][i] = 1
        else:
            vc['comment_{}_n'.format(j)][i] = (vc['comment_{}_likes'.format(j)][i]-mi)/(ma-mi)

In [126]:
vc

,comment_1_likes,comment_2_likes,comment_3_likes,comment_4_likes,comment_5_likes,comment_6_likes,comment_7_likes,comment_8_likes,comment_9_likes,comment_10_likes,...,comment_11_n,comment_12_n,comment_13_n,comment_14_n,comment_15_n,comment_16_n,comment_17_n,comment_18_n,comment_19_n,comment_20_n
0,2100,1800,40,12,2500,587,37,66,33,2,...,0.002400,0.002400,0.013200,0.000800,0.000400,0.000800,0.000000,0.000000,0.015200,0.000400
1,982,3,0,438,1100,342,2000,687,152,37,...,0.050500,0.051000,0.202500,0.023500,0.019000,0.018000,0.023500,0.047500,0.078000,0.014500
2,1100,1000,2800,1500,2000,1100,1100,544,300,284,...,0.191251,0.112798,0.005785,0.055676,0.030007,0.145336,0.003615,0.000000,0.042299,0.071945
3,1500,474,31,4,41,163,123,211,31,11,...,0.013369,0.016043,0.012701,0.213235,0.051471,0.017380,0.014037,0.007353,0.025401,0.183824
4,139,368,1300,44,788,15,1,106,2,92,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000769,0.000769,0.032308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36958,13000,2200,52000,2300,1500,267,1200,112,1400,595,...,0.011905,0.003866,0.001731,0.012539,0.049927,0.000308,0.004520,0.001731,0.000000,0.017155
36959,202,1500,199,15,253,9,323,676,102,6,...,0.057333,0.002667,0.004000,0.154667,0.115333,0.000000,0.666667,0.002000,0.060667,0.006667
36960,4700,298,7,8,110,83,4200,93,174,7,...,0.000412,0.002530,0.046249,0.000294,0.000177,0.003001,0.000000,0.001706,1.000000,0.001589
36961,3000,224,37,1700,223,794,13,132,2,348,...,0.088667,0.004333,0.010333,0.000333,0.002000,0.000000,0.001000,0.001000,0.007667,0.063333
36962,203,2200,1700,715,199,84,1300,382,40,141,...,0.010919,0.000000,0.636033,0.434941,0.030937,0.041401,0.140127,0.030482,0.253412,0.002275

In [129]:
for j in vc.columns:
    print(j, " ", vc[j][0])

comment_1_likes   2100
comment_2_likes   1800
comment_3_likes   40
comment_4_likes   12
comment_5_likes   2500
comment_6_likes   587
comment_7_likes   37
comment_8_likes   66
comment_9_likes   33
comment_10_likes   2
comment_11_likes   6
comment_12_likes   6
comment_13_likes   33
comment_14_likes   2
comment_15_likes   1
comment_16_likes   2
comment_17_likes   0
comment_18_likes   0
comment_19_likes   38
comment_20_likes   1
comment_1_rate   1
comment_2_rate   5
comment_3_rate   5
comment_4_rate   5
comment_5_rate   4
comment_6_rate   5
comment_7_rate   4
comment_8_rate   5
comment_9_rate   5
comment_10_rate   2
comment_11_rate   3
comment_12_rate   5
comment_13_rate   5
comment_14_rate   5
comment_15_rate   5
comment_16_rate   5
comment_17_rate   5
comment_18_rate   5
comment_19_rate   5
comment_20_rate   5
view_count   1048888
likes   19515
comment_count   1319
dislikes   226
comment_rate   4
comment_1_n   0.84
comment_2_n   0.72
comment_3_n   0.016
comment_4_n   0.0048
comment_5_n   1.0
comment_6_n   0.2348
comment_7_n   0.0148
comment_8_n   0.0264
comment_9_n   0.0132
comment_10_n   0.0008
comment_11_n   0.0024
comment_12_n   0.0024
comment_13_n   0.0132
comment_14_n   0.0008
comment_15_n   0.0004
comment_16_n   0.0008
comment_17_n   0.0
comment_18_n   0.0
comment_19_n   0.0152
comment_20_n   0.0004

In [132]:

for i in range(0,36963):
    for j in range(1,21):
        vc['comment_{}_rate'.format(j)][i] = vc['comment_{}_rate'.format(j)][i]*vc['comment_{}_n'.format(j)][i]

/var/folders/d7/ds61x0l51tv09_l2vtf7hm9r0000gn/T/ipykernel_56139/2946466172.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vc['comment_{}_rate'.format(j)][i] = vc['comment_{}_rate'.format(j)][i]*vc['comment_{}_n'.format(j)][i]

In [133]:
for j in vc.columns:
    print(j, " ", vc[j][0])

comment_1_likes   1764.0
comment_2_likes   1296.0
comment_3_likes   0.64
comment_4_likes   0.0576
comment_5_likes   2500.0
comment_6_likes   137.82760000000002
comment_7_likes   0.5476
comment_8_likes   1.7424
comment_9_likes   0.4356
comment_10_likes   0.0016
comment_11_likes   0.0144
comment_12_likes   0.0144
comment_13_likes   0.4356
comment_14_likes   0.0016
comment_15_likes   0.0004
comment_16_likes   0.0016
comment_17_likes   0.0
comment_18_likes   0.0
comment_19_likes   0.5776
comment_20_likes   0.0004
comment_1_rate   0.84
comment_2_rate   3.5999999999999996
comment_3_rate   0.08
comment_4_rate   0.023999999999999997
comment_5_rate   4.0
comment_6_rate   1.174
comment_7_rate   0.0592
comment_8_rate   0.132
comment_9_rate   0.066
comment_10_rate   0.0016
comment_11_rate   0.0072
comment_12_rate   0.011999999999999999
comment_13_rate   0.066
comment_14_rate   0.004
comment_15_rate   0.002
comment_16_rate   0.004
comment_17_rate   0.0
comment_18_rate   0.0
comment_19_rate   0.076
comment_20_rate   0.002
view_count   1048888
likes   19515
comment_count   1319
dislikes   226
comment_rate   4
comment_1_n   0.84
comment_2_n   0.72
comment_3_n   0.016
comment_4_n   0.0048
comment_5_n   1.0
comment_6_n   0.2348
comment_7_n   0.0148
comment_8_n   0.0264
comment_9_n   0.0132
comment_10_n   0.0008
comment_11_n   0.0024
comment_12_n   0.0024
comment_13_n   0.0132
comment_14_n   0.0008
comment_15_n   0.0004
comment_16_n   0.0008
comment_17_n   0.0
comment_18_n   0.0
comment_19_n   0.0152
comment_20_n   0.0004

In [134]:
for j in range(1,21):
    vc = vc.drop(columns="comment_{}_likes".format(j))
    vc = vc.drop(columns="comment_{}_n".format(j))

In [135]:
vc

,comment_1_rate,comment_2_rate,comment_3_rate,comment_4_rate,comment_5_rate,comment_6_rate,comment_7_rate,comment_8_rate,comment_9_rate,comment_10_rate,...,comment_16_rate,comment_17_rate,comment_18_rate,comment_19_rate,comment_20_rate,view_count,likes,comment_count,dislikes,comment_rate
0,0.840000,3.600000,0.080000,0.024000,4.000000,1.174000,0.059200,0.132000,0.066000,0.001600,...,0.004000,0.000000,0.000000,0.076000,0.002000,1048888,19515,1319,226,4
1,2.455000,0.007500,0.000000,1.095000,0.550000,0.855000,5.000000,1.717500,0.380000,0.092500,...,0.090000,0.117500,0.237500,0.390000,0.072500,15352638,359277,18729,7479,5
2,1.926970,1.047722,5.000000,2.650036,3.553868,1.926970,1.926970,0.921909,0.384671,0.361533,...,0.726681,0.018077,0.000000,0.211497,0.359725,925281,11212,831,401,5
3,1.000000,1.570856,0.090241,0.000000,0.123663,0.531417,0.397727,0.691845,0.090241,0.023396,...,0.086898,0.070187,0.036765,0.076203,0.919118,2641597,39131,3745,441,4
4,0.534615,1.132308,3.000000,0.033846,0.606154,0.057692,0.002308,0.081538,0.007692,0.141538,...,0.000000,0.000000,0.003846,0.003846,0.161538,271736,16622,743,90,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36958,0.249942,0.042234,5.000000,0.044157,0.115086,0.025290,0.023002,0.010385,0.107393,0.056831,...,0.001539,0.022598,0.001731,0.000000,0.085776,120408275,2180780,81360,35871,3
36959,0.673333,1.000000,0.663333,0.050000,0.843333,0.030000,1.076667,2.253333,0.340000,0.020000,...,0.000000,2.666667,0.002000,0.121333,0.033333,2841917,20759,2624,1049,4
36960,0.828773,0.086202,0.000118,0.000883,0.030891,0.022948,1.234187,0.025890,0.049721,0.000588,...,0.012004,0.000000,0.006826,5.000000,0.007944,13346678,720854,90616,4426,5
36961,5.000000,0.149333,0.061667,0.566667,0.297333,1.323333,0.017333,0.176000,0.000667,0.464000,...,0.000000,0.002000,0.005000,0.007667,0.126667,252057,19198,1471,1234,3
36962,0.274340,5.000000,3.090082,1.621929,0.448135,0.186533,2.952684,0.864422,0.086442,0.063239,...,0.124204,0.560510,0.030482,1.267061,0.011374,2252090,34063,2004,868,4

In [136]:
vc1

,comment_1_likes,comment_2_likes,comment_3_likes,comment_4_likes,comment_5_likes,comment_6_likes,comment_7_likes,comment_8_likes,comment_9_likes,comment_10_likes,...,comment_16_likes,comment_17_likes,comment_18_likes,comment_19_likes,comment_20_likes,view_count,likes,comment_count,dislikes,comment_rate
0,2100,1800,40,12,2500,587,37,66,33,2,...,2,0,0,38,1,1048888,19515,1319,226,4
1,982,3,0,438,1100,342,2000,687,152,37,...,36,47,95,156,29,15352638,359277,18729,7479,5
2,1100,1000,2800,1500,2000,1100,1100,544,300,284,...,436,44,34,151,233,925281,11212,831,401,5
3,1500,474,31,4,41,163,123,211,31,11,...,30,25,15,42,279,2641597,39131,3745,441,4
4,139,368,1300,44,788,15,1,106,2,92,...,0,0,1,1,42,271736,16622,743,90,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36958,13000,2200,52000,2300,1500,267,1200,112,1400,595,...,20,239,94,4,896,120408275,2180780,81360,35871,3
36959,202,1500,199,15,253,9,323,676,102,6,...,0,1000,3,91,10,2841917,20759,2624,1049,4
36960,4700,298,7,8,110,83,4200,93,174,7,...,56,5,34,17000,32,13346678,720854,90616,4426,5
36961,3000,224,37,1700,223,794,13,132,2,348,...,0,3,3,23,190,252057,19198,1471,1234,3
36962,203,2200,1700,715,199,84,1300,382,40,141,...,93,310,69,559,7,2252090,34063,2004,868,4

In [137]:
vc2

       view_count    likes  comment_count  dislikes  comment_rate
0         1048888    19515           1319       226             4
1        15352638   359277          18729      7479             5
2          925281    11212            831       401             5
3         2641597    39131           3745       441             4
4          271736    16622            743        90             4
...           ...      ...            ...       ...           ...
36958   120408275  2180780          81360     35871             3
36959     2841917    20759           2624      1049             4
36960    13346678   720854          90616      4426             5
36961      252057    19198           1471      1234             3
36962     2252090    34063           2004       868             4

[36963 rows x 5 columns]

# Saving files to run regression models on

In [138]:
#has normalized likes
vc.to_csv("vc.csv")
#just has likes and a single column for comment_rate(merged rate)
vc1.to_csv("vc1.csv")
# don't have any likes but has a single column for comment_rate(merged rate)
vc2.to_csv("vc2.csv")